# Generated by Django 6.0.2 on 2026-02-25 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_atproto_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='atproto_uri',
            field=models.CharField(blank=True, max_length=512, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ATProtoSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('dpop_private_pem', models.TextField(blank=True)),
                ('dpop_jwk', models.JSONField(blank=True, default=dict)),
                ('token_endpoint', models.URLField(blank=True)),
                ('dpop_nonce', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atproto_session', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
