services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bluebell-frontend-blue
    restart: unless-stopped
    env_file: .env
    environment:
      PORT: "3000"
      BUILD_MODE: prod
    labels:
      deployment: blue
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bluebell

networks:
  bluebell:
    external: true
    name: bluebell_bluebell
