# Generated by Django 6.0.2 on 2026-02-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boostallocation',
            name='atproto_uri',
            field=models.CharField(blank=True, max_length=512, null=True, unique=True),
        ),
    ]
