# Generated by Django 6.0.2 on 2026-02-25 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0004_add_atproto_uri'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossPublishResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('steam', 'Steam'), ('itchio', 'itch.io'), ('substack', 'Substack')], max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('external_url', models.URLField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cross_publishes', to='content.post')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cross_publishes', to='content.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_publish_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalMetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('watch_time_seconds', models.IntegerField(default=0)),
                ('revenue_cents', models.IntegerField(default=0)),
                ('snapshot_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cross_publish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_snapshots', to='integrations.crosspublishresult')),
            ],
            options={
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='PlatformConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('steam', 'Steam'), ('itchio', 'itch.io'), ('substack', 'Substack')], max_length=20)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('api_key', models.TextField(blank=True)),
                ('platform_user_id', models.CharField(blank=True, max_length=255)),
                ('platform_username', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_connections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='crosspublishresult',
            index=models.Index(fields=['user', 'platform'], name='integration_user_id_32277b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='externalmetricsnapshot',
            unique_together={('cross_publish', 'snapshot_date')},
        ),
        migrations.AlterUniqueTogether(
            name='platformconnection',
            unique_together={('user', 'platform')},
        ),
    ]
