# Generated by Django 6.0.2 on 2026-02-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_post_audio_file_post_body_html_post_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='atproto_uri',
            field=models.CharField(blank=True, max_length=512, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='atproto_uri',
            field=models.CharField(blank=True, max_length=512, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='atproto_uri',
            field=models.CharField(blank=True, max_length=512, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='atproto_uri',
            field=models.CharField(blank=True, max_length=512, null=True, unique=True),
        ),
    ]
