// SPDX-License-Identifier: Apache-2.0
/**
 * Name→row resolution for suites built on the account fixture.
 *
 * `createAccount(name)` gives the account a handle that is not always derivable from the
 * name — a name the server would refuse (over 18 characters, say) is silently rewritten or
 * generated by `localHandleName`, and the result hangs under a suffix only the node reports.
 * A suite holding only the name (most of them — fixture setup passes names around) resolves
 * the account by email, which the fixture keeps at the deterministic `<name>@example.com`.
 */

import { db } from "@anthers/db/client";
import { users } from "@anthers/db/schema";
import type { SQL } from "drizzle-orm";
import { eq, inArray } from "drizzle-orm";

/**
 * A drizzle condition matching one fixture account by the name it was created with, using its
 * email — the handle a name actually got is not always derivable from the name.
 */
export function fixtureByName(name: string): SQL {
	return eq(users.email, `${name}@example.com`);
}

/** The same, for a list of names. */
export function fixtureByNames(names: string[]): SQL {
	return inArray(
		users.email,
		names.map((n) => `${n}@example.com`),
	);
}

/**
 * Fixture account ids by creation name. Deleting by email hits the same rows, but much of
 * what hangs off an account is `ON DELETE SET NULL` rather than cascade — Works and posts
 * outlive the account by design — so anything that should go with the account has to be
 * deleted by owner id FIRST, which takes having the ids.
 */
export async function fixtureIdsByNames(names: string[]): Promise<number[]> {
	if (names.length === 0) return [];
	const rows = await db.select({ id: users.id }).from(users).where(fixtureByNames(names));
	return rows.map((r) => r.id);
}

/** The fixture account row made with `createAccount(name)`, by its deterministic email. */
const rowsByName = new Map<string, Promise<typeof users.$inferSelect>>();

export function userByName(name: string) {
	// Memoized: a suite builds profile and catalog addresses from handles and looks the same
	// account up across many tests. The handle itself cannot change under a name — the
	// fixture issues it once — so caching the row is safe for that purpose; a suite that
	// deletes an account mid-run must not assert on it afterward either way.
	let row = rowsByName.get(name);
	if (!row) {
		row = db
			.select()
			.from(users)
			.where(eq(users.email, `${name}@example.com`))
			.then(([r]) => {
				if (!r) throw new Error(`no fixture account named ${name} (${name}@example.com)`);
				return r;
			});
		rowsByName.set(name, row);
	}
	return row;
}

/**
 * The handle `createAccount(name)` actually got — what profile (`/users/:handle`),
 * follow/block and catalog (`/catalog/:handle`) addresses are built from. Sync once any
 * account has been awaited: the first call goes through `userByName`, and a suite that
 * needs the handle has always just created the account.
 */
export async function handleOf(name: string): Promise<string> {
	return (await userByName(name)).atprotoHandle;
}

/** Just the id, for the (many) suites that look a fixture user up only to key on it. */
export async function userIdByName(name: string): Promise<number> {
	return (await userByName(name)).id;
}
