// SPDX-License-Identifier: AGPL-3.0-or-later
/**
 * Signature verification for the Resend delivery webhook.
 *
 * 🚨 **This runs before authentication, on a public endpoint, and it is the only thing
 * standing between a stranger and our record of whether a safety alert was delivered.**
 * Everything else in the request is attacker-controlled. So each rule of the Standard
 * Webhooks scheme gets its own case rather than one happy-path test — a verifier that
 * accepts a valid signature is not the property worth pinning; a verifier that rejects
 * every invalid one is.
 *
 * ⚠️ **The vector below is generated by our own signer**, which proves round-trip
 * consistency and does NOT prove conformance to the specification — if the signed string
 * or the key derivation were both wrong in the same way, these would still pass. What
 * guards conformance is the documented construction written out in
 * `lib/standard-webhooks.ts` plus one case here that pins the exact signed string against
 * a hand-computed HMAC, so a change to either half has to be deliberate.
 */

import { describe, expect, it } from "bun:test";
import { createHmac } from "node:crypto";
import {
	signStandardWebhook,
	standardWebhookHeaders,
	verifyStandardWebhook,
} from "../lib/standard-webhooks.js";

/**
 * 🚨 **Never let a test fixture look like a real credential.** The first version of this
 * used `whsec_` followed by 32 alphanumerics — which is Stripe's webhook-secret format
 * exactly, so GitHub secret scanning flagged it on a PUBLIC repository and a human had to
 * stop and check. Nothing had leaked; the string was invented. That is precisely the cost:
 * it spends somebody's attention, and a scanner that cries wolf teaches people to wave the
 * next alert through.
 *
 * The prefix is still exercised, because `keyFor` really does strip it — but the body
 * carries underscores and the word EXAMPLE, so it cannot match a vendor's pattern. A
 * fixture should be unmistakably a fixture at a glance.
 */
const SECRET = "whsec_EXAMPLE_ONLY_not_a_real_secret";
const ID = "msg_2Xy7bQ";
const BODY = '{"type":"email.delivered","data":{"email_id":"abc-123"}}';

function at(offsetSeconds = 0) {
	return Math.floor(Date.now() / 1000) + offsetSeconds;
}

function headersFor(ts: number, body = BODY, secret = SECRET, id = ID) {
	return {
		id,
		timestamp: String(ts),
		signature: signStandardWebhook({ secret, id, timestamp: ts, body }),
	};
}

describe("a genuine delivery", () => {
	it("accepts a correctly signed, current request", () => {
		const ts = at();
		expect(verifyStandardWebhook({ secret: SECRET, headers: headersFor(ts), body: BODY })).toEqual({
			ok: true,
		});
	});

	it("accepts when a rotating secret produces two signatures and one matches", () => {
		// Svix signs once per active secret during a rotation, so a valid request can carry
		// a signature we cannot verify alongside one we can. Requiring all to match would
		// take the endpoint down for the whole rotation window.
		const ts = at();
		const good = signStandardWebhook({ secret: SECRET, id: ID, timestamp: ts, body: BODY });
		const other = signStandardWebhook({
			secret: "whsec_EXAMPLE_ONLY_a_different_secret",
			id: ID,
			timestamp: ts,
			body: BODY,
		});
		const res = verifyStandardWebhook({
			secret: SECRET,
			headers: { id: ID, timestamp: String(ts), signature: `${other} ${good}` },
			body: BODY,
		});
		expect(res.ok).toBe(true);
	});

	it("signs the exact string the specification names", () => {
		// The one case that pins the *construction* rather than the round trip: `{id}.{ts}.{body}`,
		// HMAC-SHA256, keyed on the base64-DECODED secret, encoded base64. Computed here by
		// hand so that changing either half of the pair has to be deliberate.
		const ts = 1700000000;
		const key = Buffer.from(SECRET.slice("whsec_".length), "base64");
		const expected = createHmac("sha256", key).update(`${ID}.${ts}.${BODY}`).digest("base64");
		expect(signStandardWebhook({ secret: SECRET, id: ID, timestamp: ts, body: BODY })).toBe(
			`v1,${expected}`,
		);
	});
});

describe("everything a forger might try", () => {
	it("rejects a tampered body", () => {
		// The whole point. A signature over the original bytes must not validate a payload
		// claiming a different email was delivered.
		const ts = at();
		const res = verifyStandardWebhook({
			secret: SECRET,
			headers: headersFor(ts),
			body: '{"type":"email.delivered","data":{"email_id":"SOMEONE-ELSES"}}',
		});
		expect(res).toEqual({ ok: false, reason: "no_matching_signature" });
	});

	it("rejects a signature made with a different secret", () => {
		const ts = at();
		const res = verifyStandardWebhook({
			secret: SECRET,
			headers: headersFor(ts, BODY, "whsec_EXAMPLE_ONLY_a_different_secret"),
			body: BODY,
		});
		expect(res.ok).toBe(false);
	});

	it("rejects a replayed request once it is stale", () => {
		// Without this a captured request is valid forever, which is the difference between
		// a signature and a bearer token.
		const ts = at(-(6 * 60));
		const res = verifyStandardWebhook({ secret: SECRET, headers: headersFor(ts), body: BODY });
		expect(res).toEqual({ ok: false, reason: "timestamp_outside_tolerance" });
	});

	it("rejects a timestamp from the future, not just a stale one", () => {
		// Checking only the past leaves a capture replayable by anyone who can skew a clock
		// forward, so the tolerance is two-sided.
		const ts = at(6 * 60);
		const res = verifyStandardWebhook({ secret: SECRET, headers: headersFor(ts), body: BODY });
		expect(res).toEqual({ ok: false, reason: "timestamp_outside_tolerance" });
	});

	it("rejects a request whose id differs from the one signed", () => {
		// The id is part of the signed string, so swapping it must invalidate — that is what
		// makes each delivery individually identified rather than interchangeable.
		const ts = at();
		const signed = headersFor(ts);
		const res = verifyStandardWebhook({
			secret: SECRET,
			headers: { ...signed, id: "msg_someone_else" },
			body: BODY,
		});
		expect(res.ok).toBe(false);
	});

	it("refuses when any header is missing", () => {
		const ts = at();
		const full = headersFor(ts);
		for (const drop of ["id", "timestamp", "signature"] as const) {
			const headers = { ...full, [drop]: undefined };
			expect(verifyStandardWebhook({ secret: SECRET, headers, body: BODY })).toEqual({
				ok: false,
				reason: "missing_headers",
			});
		}
	});

	it("refuses when no secret is configured, rather than accepting anything", () => {
		// 🚨 Fails CLOSED. An unset secret must never mean "skip verification" — that is the
		// shape of the empty-SITE_PASSWORD incident, where a missing value removed a
		// protection instead of denying.
		const ts = at();
		expect(verifyStandardWebhook({ secret: "", headers: headersFor(ts), body: BODY })).toEqual({
			ok: false,
			reason: "no_secret",
		});
	});

	it("rejects a non-numeric timestamp instead of coercing it", () => {
		const res = verifyStandardWebhook({
			secret: SECRET,
			headers: { id: ID, timestamp: "not-a-number", signature: "v1,x" },
			body: BODY,
		});
		expect(res).toEqual({ ok: false, reason: "bad_timestamp" });
	});

	it("ignores a signature version it does not understand", () => {
		// An unknown scheme is not something to guess at. Skipping it leaves v1 still
		// required, so a forger cannot get in by inventing a version.
		const ts = at();
		const res = verifyStandardWebhook({
			secret: SECRET,
			headers: { id: ID, timestamp: String(ts), signature: "v2,anything-at-all" },
			body: BODY,
		});
		expect(res).toEqual({ ok: false, reason: "no_matching_signature" });
	});

	it("survives a malformed signature header without throwing", () => {
		const ts = at();
		for (const signature of ["", "garbage", "v1", "v1,", ",,,", "v1,not-base64!!"]) {
			const res = verifyStandardWebhook({
				secret: SECRET,
				headers: { id: ID, timestamp: String(ts), signature },
				body: BODY,
			});
			expect(res.ok).toBe(false);
		}
	});
});

describe("header naming", () => {
	it("reads both the svix and the vendor-neutral names", () => {
		// Senders migrate from `svix-*` to `webhook-*`, and the failure would look exactly
		// like a bad secret rather than like a rename.
		const svix = standardWebhookHeaders((n) => (n === "svix-id" ? "A" : undefined));
		expect(svix.id).toBe("A");
		const neutral = standardWebhookHeaders((n) => (n === "webhook-id" ? "B" : undefined));
		expect(neutral.id).toBe("B");
	});
});
