# Generated by Django 6.0.2 on 2026-02-25 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRFSubsidy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_cycle', models.DateField(help_text='First day of the billing cycle.')),
                ('estimated_hosting_cost', models.DecimalField(decimal_places=2, help_text='Estimated monthly hosting cost for this creator.', max_digits=8)),
                ('creator_earnings', models.DecimalField(decimal_places=2, help_text="Creator's total earnings during this cycle.", max_digits=8)),
                ('subsidy_amount', models.DecimalField(decimal_places=2, help_text='CRF subsidy paid to offset hosting costs.', max_digits=8)),
                ('storage_bytes', models.BigIntegerField(default=0, help_text="Total storage used by creator's content.")),
                ('project_count', models.PositiveIntegerField(default=0)),
                ('post_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crf_subsidies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-billing_cycle'],
                'unique_together': {('creator', 'billing_cycle')},
            },
        ),
    ]
