# Generated by Django 6.0.2 on 2026-02-25 08:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0004_add_atproto_uri'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameJam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('theme', models.CharField(blank=True, help_text='Hidden until jam starts.', max_length=255)),
                ('cover_image', models.ImageField(blank=True, upload_to='jams/covers/')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('voting_end_at', models.DateTimeField()),
                ('max_team_size', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('allow_late_submissions', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_jams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_at'],
            },
        ),
        migrations.CreateModel(
            name='JamEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='jams.gamejam')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jam_entries', to='content.project')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jam_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('jam', 'project')},
            },
        ),
        migrations.CreateModel(
            name='JamVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='jams.jamentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jam_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('entry', 'user')},
            },
        ),
    ]
