// SPDX-License-Identifier: AGPL-3.0-or-later
//
// GENERATED by scripts/econ-figures.ts — do not edit.
// Run `bun run econ:figures` after changing a dial in constants.ts or a formula
// in fees.ts. `make verify` fails if this file is stale.
//
// These are plain numbers on purpose: the app must not import fees.ts, which would
// pull decimal.js into the SPA bundle. Derivation happens at build time instead.

/**
 * Per-Badge decomposition of the monthly charge. Exact, not illustrative — it stopped
 * depending on a reference streamer's watch-hours when the bandwidth term went.
 */
export const BADGE_TABLE = [
	{
		badge: "Root",
		seeds: 1,
		charge: "3.00",
		timePool: "1.50",
		payments: "0.39",
		remainder: "1.11",
	},
	{
		badge: "Sprout",
		seeds: 2,
		charge: "6.00",
		timePool: "3.00",
		payments: "0.47",
		remainder: "2.53",
	},
	{
		badge: "Petal",
		seeds: 3,
		charge: "9.00",
		timePool: "4.50",
		payments: "0.56",
		remainder: "3.94",
	},
	{
		badge: "Blossom",
		seeds: 4,
		charge: "12.00",
		timePool: "6.00",
		payments: "0.65",
		remainder: "5.35",
	},
] as const;

/**
 * Direct-sale take-homes. `sizeGiB` is context for the row, NOT an input to the money:
 * delivery is free, so two rows at the same price agree whatever their size.
 */
export const SALE_TABLE = [
	{
		label: "game-10-1gib",
		price: "10.00",
		sizeGiB: 1,
		creatorReceives: "9.41",
		cardFee: "0.59",
	},
	{
		label: "game-10-2gib",
		price: "10.00",
		sizeGiB: 2,
		creatorReceives: "9.41",
		cardFee: "0.59",
	},
	{
		label: "game-20-10gib",
		price: "20.00",
		sizeGiB: 10,
		creatorReceives: "19.12",
		cardFee: "0.88",
	},
	{
		label: "album-10-1gib",
		price: "10.00",
		sizeGiB: 1,
		creatorReceives: "9.41",
		cardFee: "0.59",
	},
	{
		label: "merch-25-physical",
		price: "25.00",
		sizeGiB: 0,
		creatorReceives: "23.97",
		cardFee: "1.03",
	},
] as const;

/** The sample monthly receipt: a Sprout who also directs two Seeds. */
export const SAMPLE_RECEIPT = {
	anthersSeeds: 2,
	creatorSeeds: 2,
	directedGross: "6.00",
	directedNet: "5.67",
	timePool: "3.00",
	payments: "0.65",
	paymentsAnthers: "0.32",
	paymentsCreator: "0.33",
	remainder: "2.68",
	seedsSubtotal: "12.00",
	salesTax: "0.78",
	totalBilled: "12.78",
	toCreators: "8.67",
} as const;

/** A lone directed Seed — the worst case, and what creator-facing copy quotes. */
export const DIRECTED_SEED_WORST_CASE = {
	gross: "3.00",
	net: "2.61",
	cardFee: "0.39",
} as const;
