# Generated by Django 6.0.2 on 2026-02-25 01:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0003_post_audio_file_post_body_html_post_content_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.DecimalField(decimal_places=2, help_text='Minimum monthly boost amount to unlock this gate.', max_digits=5)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['threshold'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('window', 'Window'), ('base', 'Base'), ('supporter', 'Supporter'), ('advocate', 'Advocate'), ('champion', 'Champion')], default='window', max_length=20)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttentionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('play', 'Play'), ('watch', 'Watch'), ('read', 'Read'), ('listen', 'Listen')], max_length=20)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_attention', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attention_events', to='content.post')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attention_events', to='content.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attention_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='idx_attention_user_date'), models.Index(fields=['creator', 'created_at'], name='idx_attention_creator_date')],
            },
        ),
        migrations.CreateModel(
            name='BoostAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('billing_cycle', models.DateField(help_text='First day of the billing cycle this allocation applies to.')),
                ('is_locked', models.BooleanField(default=False, help_text='Locked after first manual adjustment in a billing cycle.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_boosts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boost_allocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-billing_cycle', '-amount'],
                'unique_together': {('user', 'creator', 'billing_cycle')},
            },
        ),
        migrations.CreateModel(
            name='PoolDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_cycle', models.DateField(help_text='First day of the billing cycle.')),
                ('pool_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount from attention-based creator pool.', max_digits=8)),
                ('boost_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount from manual boost allocation.', max_digits=8)),
                ('attention_seconds', models.PositiveIntegerField(default=0, help_text='Total attention time (seconds) subscriber spent on this creator.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_earnings', to=settings.AUTH_USER_MODEL)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_distributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-billing_cycle', '-pool_amount'],
                'unique_together': {('subscriber', 'creator', 'billing_cycle')},
            },
        ),
    ]
