// SPDX-License-Identifier: Apache-2.0
/**
 * Produce the web-sized logo files the app ships from the logo's own exports, and record
 * what each was made from.
 *
 *   bun run brand:logo
 *
 * `packages/brand/logo/base/` and `preps/` are the logo: Parker's PSDs, each beside the
 * PNGs exported from it, and the only place the art is ever edited. Those exports are
 * 2560×1440 and several hundred kilobytes each, which is right for a source and wrong for
 * a navbar, so this trims each lockup to its artwork, scales it to a few times the largest
 * size it is drawn at, and cuts the tab and home-screen icons from the 1:1 thumb.
 *
 * **Run it after re-exporting from a PSD, and commit what it writes.** The outputs are
 * committed rather than built so the site builds without an image library on the deploy
 * path. `logo/web/manifest.json` records the SHA-256 of every source and every output,
 * and `brand-logo.test.ts` fails when either no longer matches — which is what makes a
 * re-export without a rerun, or a hand-edited output, impossible to miss.
 */

import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import sharp from "sharp";

const REPO = join(import.meta.dir, "..");
const LOGO = "packages/brand/logo";

type Output = {
	/** Repository-relative path of the file the app uses. */
	file: string;
	/** Repository-relative path of the export it is made from. */
	source: string;
	/** Trim to the artwork and scale to this height (lockups), or cover this square (icons). */
	height: number;
	kind: "lockup" | "icon";
};

// Heights are roughly three times the tallest place each cut is drawn — `<Logo>` is sized
// by height utilities, up to `h-15` for the one-line cut, `h-24` for the tagline cut in
// the footer and `h-28` for the stacked cut on the site gate — so a high-density screen
// never scales one up.
const LOCKUPS: [cut: string, sourceName: string, height: number][] = [
	["oneline", "hone", 180],
	["tagline", "htwo", 288],
	["stacked", "vert", 360],
];

export const OUTPUTS: Output[] = [
	...LOCKUPS.flatMap(([cut, name, height]) =>
		(["light", "dark"] as const).map((theme) => ({
			file: `${LOGO}/web/lockup-${cut}-${theme}.png`,
			source: `${LOGO}/base/antherslogo_${name}_for${theme}_trans.png`,
			height,
			kind: "lockup" as const,
		})),
	),
	...[32, 64, 180].map((size) => ({
		file: `${LOGO}/web/icon-${size}.png`,
		source: `${LOGO}/preps/antherslogo_thumb1x1_light.png`,
		height: size,
		kind: "icon" as const,
	})),
	// 🚨 A stable URL, not a bundled asset: the identity server's email header points at it
	// by address. See apps/web/public/brand/README.md before renaming it.
	{
		file: "apps/web/public/brand/anthers-mark-256.png",
		source: `${LOGO}/preps/antherslogo_thumb1x1_light.png`,
		height: 256,
		kind: "icon",
	},
];

export const MANIFEST = `${LOGO}/web/manifest.json`;

export const sha256 = (path: string) =>
	createHash("sha256")
		.update(readFileSync(join(REPO, path)))
		.digest("hex");

/** The tight bounding box of every pixel with any opacity at all. */
async function alphaBox(path: string) {
	const { data, info } = await sharp(path)
		.ensureAlpha()
		.raw()
		.toBuffer({ resolveWithObject: true });
	let [left, top, right, bottom] = [info.width, info.height, -1, -1];
	for (let y = 0; y < info.height; y++) {
		for (let x = 0; x < info.width; x++) {
			if (data[(y * info.width + x) * 4 + 3] === 0) continue;
			left = Math.min(left, x);
			right = Math.max(right, x);
			top = Math.min(top, y);
			bottom = Math.max(bottom, y);
		}
	}
	if (right < 0) throw new Error(`${path} is fully transparent`);
	return { left, top, width: right - left + 1, height: bottom - top + 1 };
}

async function render(o: Output) {
	const src = join(REPO, o.source);
	const image =
		o.kind === "lockup"
			? sharp(src)
					.extract(await alphaBox(src))
					.resize({ height: o.height })
			: sharp(src).resize(o.height, o.height, { fit: "cover" });
	mkdirSync(dirname(join(REPO, o.file)), { recursive: true });
	await image.png({ compressionLevel: 9, palette: true, quality: 100 }).toFile(join(REPO, o.file));
}

if (import.meta.main) {
	for (const o of OUTPUTS) {
		await render(o);
		const { width, height } = await sharp(join(REPO, o.file)).metadata();
		console.log(`  ${o.file}  ${width}×${height}  ← ${o.source}`);
	}
	const manifest = {
		note: "Generated by `bun run brand:logo`. Do not edit; rerun it after re-exporting from a PSD.",
		outputs: OUTPUTS.map((o) => ({
			file: o.file,
			source: o.source,
			sourceSha256: sha256(o.source),
			sha256: sha256(o.file),
		})),
	};
	writeFileSync(join(REPO, MANIFEST), `${JSON.stringify(manifest, null, "\t")}\n`);
	console.log(`  ${MANIFEST}`);
}
