// SPDX-License-Identifier: AGPL-3.0-or-later
/**
 * Generate the attribution of record in `packages/brand/THIRD-PARTY.md`, and assert
 * that every icon this repository redistributes may actually be redistributed.
 *
 *     bun run brand:attribution           # rewrite the generated block
 *     bun run brand:attribution --check   # fail if it has drifted (CI, make verify)
 *
 * 🚨 **The licensing check is an assertion here, not a caution in a task body.** Noun
 * Project terms differ per asset between public domain and attribution-required, and
 * the old arrangement was a hand-maintained table plus a reminder to check each pick
 * — which drifts the first time somebody adds an icon and forgets. An unrecognized
 * license fails this command rather than passing quietly.
 *
 * ⚠️ **Needs no API key and no private library**, so a fork and a CI runner can both
 * run it. It reads two committed files: the curated set and its provenance.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
	absolute,
	auditCurated,
	BRAND_DIR,
	LICENSES,
	readCurated,
	readProvenance,
} from "./noun/provenance";

const THIRD_PARTY = join(BRAND_DIR, "THIRD-PARTY.md");
const KEY = "icons";
const BEGIN = `<!-- brand:begin ${KEY} -->`;
const END = `<!-- brand:end ${KEY} -->`;

const check = Bun.argv.includes("--check");

// The licensing assertion itself lives in `auditCurated` so it can be tested against a
// license string that does not exist — the case that matters and that no real fixture has.
const { failures, rows } = auditCurated(readCurated(), readProvenance());

// ── The generated block ──────────────────────────────────────────────────────

function creditLine(): string {
	// Each name bolded on its own, so the credit stays readable when it is lifted out of
	// this file and pasted somewhere else — which is what a credit line is for.
	const names = [...new Set(rows.map((r) => r.p.creator.name))]
		.sort((a, b) => a.localeCompare(b, undefined, { sensitivity: "base" }))
		.map((n) => `**${n}**`);
	const listed =
		names.length <= 1
			? (names[0] ?? "—")
			: `${names.slice(0, -1).join(", ")} and ${names[names.length - 1]}`;
	const licenses = [...new Set(rows.map((r) => r.p.license))];
	const only = licenses.length === 1 ? LICENSES[licenses[0] as string] : undefined;
	const terms = only
		? only.url
			? `, licensed [${only.label}](${only.url})`
			: `, ${only.label}`
		: ", each licensed as named in the table below";
	return `> Icon artwork by ${listed}, via [The Noun Project](${absolute(undefined)})${terms}.`;
}

function table(): string {
	const head = "| Icon | Term | Creator | License |\n|---|---|---|---|";
	const body = [...rows]
		.sort((a, b) => a.id.localeCompare(b.id))
		.map(({ id, p }) => {
			const license = LICENSES[p.license] as { label: string; url: string | null };
			const term = `[${p.term}](${absolute(p.permalink)})`;
			const creator = p.creator.permalink
				? `[${p.creator.name}](${absolute(p.creator.permalink)})`
				: p.creator.name;
			const licensed = license.url ? `[${license.label}](${license.url})` : license.label;
			return `| \`${id}\` | ${term} | ${creator} | ${licensed} |`;
		})
		.join("\n");
	return `${head}\n${body}`;
}

function render(): string {
	return [
		`${rows.length} icons, each named with its artist and its terms. This is the attribution of record: it travels with the redistribution, and the redistribution happens here.`,
		"",
		creditLine(),
		"",
		table(),
	].join("\n");
}

// ── Splice and reconcile ─────────────────────────────────────────────────────

if (failures.length === 0) {
	const source = readFileSync(THIRD_PARTY, "utf8");
	const i = source.indexOf(BEGIN);
	const k = source.indexOf(END);
	if (i === -1 || k === -1) {
		// 🚨 A failure rather than a warning, on the same reasoning `econ-figures` gives:
		// a block whose markers are gone is a target this guard has silently lost, and
		// "never checked" is exactly the state a hand-maintained table was already in.
		failures.push(`THIRD-PARTY.md — no ${BEGIN} markers (block deleted?)`);
	} else {
		const note = "<!-- GENERATED by `bun run brand:attribution` — do not edit by hand. -->";
		const next = `${source.slice(0, i + BEGIN.length)}\n${note}\n\n${render()}\n\n${source.slice(k)}`;
		if (next !== source) {
			if (check) failures.push("THIRD-PARTY.md — the attribution block is out of date");
			else {
				writeFileSync(THIRD_PARTY, next);
				console.log("  wrote packages/brand/THIRD-PARTY.md");
			}
		}
	}
}

if (failures.length > 0) {
	console.error("brand:attribution — failed:");
	for (const f of failures) console.error(`  • ${f}`);
	process.exit(1);
}
console.log(`brand:attribution: ${rows.length} icons, all redistributable, attribution current.`);
