// SPDX-License-Identifier: AGPL-3.0-or-later
/**
 * Render every published money figure from the model, into both places that quote it.
 *
 *   bun run econ:figures           # write
 *   bun run econ:figures --check   # fail if anything has drifted (CI / make verify)
 *
 * Two outputs:
 *
 *  1. `packages/shared/src/figures.generated.ts` — plain numbers for the app. Plain,
 *     because **the SPA bundle must never import `fees.ts`**: that is the one import
 *     that pulls decimal.js in. Generating the figures gets derivation without the
 *     dependency, which is why this is a codegen step rather than a runtime import.
 *
 *     To check that it stayed out, do NOT grep the bundle for `toDecimalPlaces` —
 *     recharts ships **decimal.js-light**, which has that method too, so the obvious
 *     test reports a leak that isn't there (it fooled me on 2026-08-08). Grep for
 *     `cbrt` or `toFraction`, which only full decimal.js has. Both are 0 today.
 *
 *  2. The wiki tables and the sample receipt, written between HTML-comment markers
 *     in the docs that publish them. Same pattern the vault already uses for roadmap
 *     bars: generated regions are never hand-edited.
 *
 * Why it exists: the 2026-08-03 pricing revamp swept these by hand and missed three
 * of them, which then sat in the "source of truth" doc overstating the remainder by
 * exactly the card fee for five days. A sweep cannot be trusted to be complete.
 */
import { existsSync } from "node:fs";
import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import {
	CARD_FLAT,
	CARD_RATE,
	FREE_STORAGE_GIB,
	SALES_TAX_RATE,
	SEED_PRICE,
	TIME_POOL_PER_SEED,
} from "../packages/shared/src/constants.js";
import {
	badgeTable,
	cartSaving,
	creatorReceipt,
	directedSeedWorstCase,
	FIXED_MONTHLY_OVERHEAD,
	PAYING_BADGE_MIX,
	purchaseExamples,
	saleTable,
	sampleReceipt,
	selfSufficiency,
} from "../packages/shared/src/scenarios.js";

const REPO = join(import.meta.dir, "..");
const VAULT = join(process.env.HOME ?? "", "Obsidian/40-59 PhD Projects/43 Platforms/Anthers");

const check = process.argv.includes("--check");
const failures: string[] = [];

/**
 * Run the rendered module through Biome before writing it.
 *
 * Without this the generator and the linter disagree — `--check` passes while
 * `bun run lint` fails on the file the generator just produced, which is a
 * maddening way to break the build. Formatting here means the two can never
 * diverge, whatever Biome's style settings become later.
 */
async function formatted(source: string): Promise<string> {
	const proc = Bun.spawn(["bunx", "biome", "format", "--stdin-file-path=figures.generated.ts"], {
		stdin: new TextEncoder().encode(source),
		stdout: "pipe",
		stderr: "pipe",
	});
	const out = await new Response(proc.stdout).text();
	if ((await proc.exited) !== 0) {
		console.error(await new Response(proc.stderr).text());
		throw new Error("biome format failed on the generated module");
	}
	return out;
}

// ── 1. The generated module the app reads ────────────────────────────────────
function renderModule(): string {
	const badges = badgeTable();
	const sales = saleTable();
	const receipt = sampleReceipt();
	const seed = directedSeedWorstCase();
	const j = (v: unknown) => JSON.stringify(v, null, "\t").replace(/\n/g, "\n");
	return `// SPDX-License-Identifier: AGPL-3.0-or-later
//
// GENERATED by scripts/econ-figures.ts — do not edit.
// Run \`bun run econ:figures\` after changing a dial in constants.ts or a formula
// in fees.ts. \`make verify\` fails if this file is stale.
//
// These are plain numbers on purpose: the app must not import fees.ts, which would
// pull decimal.js into the SPA bundle. Derivation happens at build time instead.

/**
 * Per-Badge decomposition of the monthly charge. Exact, not illustrative — it stopped
 * depending on a reference streamer's watch-hours when the bandwidth term went.
 */
export const BADGE_TABLE = ${j(badges)} as const;

/**
 * Direct-sale take-homes. \`sizeGiB\` is context for the row, NOT an input to the money:
 * delivery is free, so two rows at the same price agree whatever their size.
 */
export const SALE_TABLE = ${j(sales)} as const;

/** The sample monthly receipt: a Sprout who also directs two Seeds. */
export const SAMPLE_RECEIPT = ${j(receipt)} as const;

/** A lone directed Seed — the worst case, and what creator-facing copy quotes. */
export const DIRECTED_SEED_WORST_CASE = ${j(seed)} as const;
`;
}

// ── 2. The wiki blocks ───────────────────────────────────────────────────────
function renderBadgeMarkdown(): string {
	const rows = badgeTable();
	const head =
		"| Badge | Seeds given to Anthers | Charge | Time Pool | Payments\\* | → Remainder |";
	const sep = "|:--|--:|--:|--:|--:|--:|";
	const body = rows.map(
		(r) =>
			`| **${r.badge}** | ${r.seeds} | $${r.charge} | $${r.timePool} | $${r.payments} | **$${r.remainder}** |`,
	);
	return [
		head,
		sep,
		...body,
		"",
		`\\* **Payments is INSIDE the charge** (since 2026-08-03), charged once per transaction at ${(CARD_RATE * 100).toFixed(1)}% + $${CARD_FLAT.toFixed(2)} and split pro-rata. Because the $${CARD_FLAT.toFixed(2)} is fixed per charge rather than per Seed, it does not scale with the Seed count — which is why the remainder grows faster than linearly.`,
		"",
		`Every row conserves exactly: Time Pool + Payments + remainder = the charge. **The remainder is the residual**, so it absorbs any change in the other two while creator pay stays fixed.`,
		"",
		`**No row depends on how much anyone watches.** A *Bandwidth* column sat between the charge and the Time Pool until 2026-08-12, priced off a representative streamer's watch-hours — so every remainder here was a scenario rather than a figure. Delivery costs $0 on R2 at any volume, so the column is gone and these numbers are exact. Watching more is free, and it takes nothing from the mission.`,
	].join("\n");
}

function renderReceiptMarkdown(): string {
	const r = sampleReceipt();
	const pad = (label: string, amount: string) =>
		`${label}${" ".repeat(Math.max(1, 62 - label.length - amount.length))}${amount}`;
	return [
		"```",
		"Your Anthers — February 2026",
		"",
		"━".repeat(66),
		pad(
			`Seeds to creators (${r.creatorSeeds} × $${SEED_PRICE}.00, directed by you)`,
			`$${r.directedGross}`,
		),
		pad(
			`  → reaching them, less their $${r.paymentsCreator} share of the card fee`,
			`$${r.directedNet}`,
		),
		"",
		pad(
			`Seeds given to Anthers (${r.anthersSeeds} · Sprout)`,
			`$${(r.anthersSeeds * SEED_PRICE).toFixed(2)}`,
		),
		pad("  Time Pool → creators you watched (by watch-time)", `$${r.timePool}`),
		pad("  Payments → this side's share of the card fee (at cost)", `$${r.paymentsAnthers}`),
		pad("  Free access & programs (the remainder)", `$${r.remainder}`),
		"─".repeat(66),
		pad("Seeds subtotal (all-in)", `$${r.seedsSubtotal}`),
		pad(
			`Sales tax (${(SALES_TAX_RATE * 100).toFixed(1)}%, the only thing added on top)`,
			`+$${r.salesTax}`,
		),
		`${" ".repeat(56)}──────`,
		pad("Total billed (prepaid, monthly)", `$${r.totalBilled}`),
		"",
		`To creators this month: $${r.toCreators}  ·  Free access & programs: $${r.remainder}  ·  Anthers keeps: $0.00`,
		"```",
	].join("\n");
}

function renderSaleMarkdown(): string {
	// One row per list price. Size used to split them — a $10 1 GiB game and a $10
	// 2 GiB game took home different amounts — and since 2026-08-12 it doesn't, so
	// keeping both would print the same row twice.
	const rows = [...new Map(saleTable().map((r) => [r.price, r])).values()];
	const seed = directedSeedWorstCase();
	return [
		"| Sale | Creator receives | Card |",
		"|:--|--:|--:|",
		...rows.map(
			(r) =>
				`| $${r.price} ${r.sizeGiB > 0 ? "digital" : "physical"} | **$${r.creatorReceives}** | $${r.cardFee} |`,
		),
		"",
		`**Download size does not appear, because it no longer changes anything.** A digital sale used to carry the first download's bandwidth at cost, and redownloads drew the buyer's own allowance; delivery is free on R2, so every download of a purchased work is included, forever, on any number of devices.`,
		"",
		`A lone directed Seed is the same shape: $${seed.gross} gross, $${seed.cardFee} card, **$${seed.net}** to the creator. Batching Seeds onto one monthly charge pays every creator on it more, because the $${CARD_FLAT.toFixed(2)} is fixed per charge.`,
		"",
		`Anthers keeps **$0.00** from every row. Creator storage is the only creator-side charge: the first ${FREE_STORAGE_GIB} GiB free, then the object-store rate plus half again.`,
	].join("\n");
}

/**
 * The creator-facing worked examples, and what a cart is worth at the small end.
 *
 * This table is the one a creator reads before deciding whether to sell here, and it
 * was typed by hand in two docs — including the Copy Style Guide, inside the very rule
 * that forbids re-typing a figure from another page.
 */
function renderPurchaseExamplesMarkdown(): string {
	const rows = purchaseExamples();
	const cart = cartSaving();
	return [
		"| Item | List | Size | Card | **Creator receives** | Deduction |",
		"|:--|--:|--:|--:|--:|--:|",
		...rows.map(
			(r) =>
				`| ${r.item} | $${r.price} | ${r.sizeLabel} | $${r.cardFee} | **$${r.creatorReceives}** | ${r.deductionPct} |`,
		),
		"",
		`**The deduction is Stripe's card fee and nothing else** — ${(CARD_RATE * 100).toFixed(1)}% + a flat $${CARD_FLAT.toFixed(2)}, paid to Stripe, with Anthers keeping $0.00 from every row. The flat part is what the percentages track: it is the whole reason a $${rows[0].price} track loses ${rows[0].deductionPct} while a $${rows[rows.length - 1].price} game loses ${rows[rows.length - 1].deductionPct}.`,
		"",
		`**Size is in the table for scale, not for money.** A digital sale used to deduct the first download's delivery at cost as well; delivery is free since 2026-08-12, so a ${rows[rows.length - 1].sizeLabel} work and a ${rows[0].sizeLabel} one at the same price pay their creator exactly the same, and every later download costs nobody anything.`,
		"",
		`**The cart is the mechanism that fixes the small end.** ${cart.count} $${cart.unitPrice} tracks bought separately lose **$${cart.separately}** to card fees; bought in one cart they lose **$${cart.inOneCart}**, and every cent of that difference goes to the creators.`,
	].join("\n");
}

/** A mid-size creator's monthly earnings, and the only cost that comes out of them. */
function renderCreatorReceiptMarkdown(): string {
	const r = creatorReceipt();
	const pad = (label: string, amount: string) =>
		`${label}${" ".repeat(Math.max(1, 62 - label.length - amount.length))}${amount}`;
	return [
		"```",
		"Your Earnings — February 2026                                  @LifeOfRiza",
		"",
		"━".repeat(66),
		pad("Time Pool (by watch-time) + directed Seeds (net of card)", `$${r.gross}`),
		pad(
			`Storage (${r.libraryGiB} GiB library − ${r.freeGiB} GiB free = ${r.billableGiB} GiB, at cost)`,
			`−$${r.storage}`,
		),
		pad("Delivery (unlimited, at any volume)", "$0.00"),
		pad("Storage charge (half again)", `−$${r.storageCharge}`),
		`${" ".repeat(54)}──────────`,
		pad("Net earnings", `$${r.net}`),
		"",
		"Payouts carry no processing (Connect transfers are free); the only",
		"deduction from a directed Seed is its share of the card fee.",
		"```",
	].join("\n");
}

/** Whether the charitable budget funds itself, as a function of the paying share. */
function renderSelfSufficiencyMarkdown(): string {
	const s = selfSufficiency();
	const mix = Object.entries(PAYING_BADGE_MIX)
		.map(([seeds, share]) => `${(Number(share) * 100).toFixed(0)}% at ${seeds}`)
		.join(", ");
	return [
		`Charitable revenue is **$${s.revenuePerPayingUser} per paying user per month**, and each paying user also carries the free-access cost of the free users beside them — **$${s.freeUserCost}/month each**, which is the subsidised Time Pool a free account funds for the creators it watches. So everything turns on the **paying share**:`,
		"",
		"| Paying share | Net per paying user | Users to solvency |",
		"|--:|--:|--:|",
		...s.rows.map(
			(r) =>
				`| ${r.sharePct} | ${r.net.startsWith("-") ? `−$${r.net.slice(1)}` : `$${r.net}`} | ${
					r.usersToSolvency === null ? "**never**" : `~${r.usersToSolvency.toLocaleString("en-US")}`
				} |`,
		),
		"",
		`**Below roughly ${s.breakEvenPct} paying, growth never closes the gap** — each new cohort costs more in free access than it brings in, so scale makes the problem worse rather than better. Above it the model self-funds, and the scale required falls away quickly.`,
		"",
		`**That floor no longer moves with how much free users watch**, and until 2026-08-12 it did. A free account's cost was its streaming bandwidth plus its Time Pool, so the generosity of the free floor and the platform's self-sufficiency were the same dial and raising one priced the other. Delivery is free on R2, the floor is gone, and what remains — the $${s.freeUserCost} Time Pool — is a flat cost per free account however much it watches. **Free access stopped having a usage-dependent price.**`,
		"",
		`Two ASSUMPTIONS drive every number here and neither is a dial: the paying-user Badge mix (${mix} Seeds) and $${FIXED_MONTHLY_OVERHEAD.toLocaleString("en-US")}/month of fixed overhead. The mix matters more than it looks — the remainder a paying user generates rises **faster than linearly** with their Seed count, because the fixed $${CARD_FLAT.toFixed(2)} of the card fee does not scale with it.`,
	].join("\n");
}

const BLOCKS: { file: string; key: string; render: () => string }[] = [
	{
		file: "50-59 Business and Finance/50 Economics & Model/50.01 Support Model Economics and Milestones.md",
		key: "badge-table",
		render: renderBadgeMarkdown,
	},
	{
		file: "50-59 Business and Finance/50 Economics & Model/50.01 Support Model Economics and Milestones.md",
		key: "sample-receipt",
		render: renderReceiptMarkdown,
	},
	{
		file: "50-59 Business and Finance/50 Economics & Model/50.01 Support Model Economics and Milestones.md",
		key: "sale-table",
		render: renderSaleMarkdown,
	},
	{
		file: "20-29 User Experience/20 Support Model/20.01 Badges and Seed Levels.md",
		key: "badge-table",
		render: renderBadgeMarkdown,
	},
	{
		file: "30-39 Creator Experience/31 Monetization/31.02 Direct Creator Purchases.md",
		key: "purchase-examples",
		render: renderPurchaseExamplesMarkdown,
	},
	{
		file: "60-69 Strategy/63 Brand/63.01 Copy Style Guide.md",
		key: "sale-table",
		render: renderSaleMarkdown,
	},
	{
		file: "50-59 Business and Finance/50 Economics & Model/50.01 Support Model Economics and Milestones.md",
		key: "creator-receipt",
		render: renderCreatorReceiptMarkdown,
	},
	{
		file: "10-19 Overview/11 Model & Mission/11.02 Free Access and Charitable Programs.md",
		key: "self-sufficiency",
		render: renderSelfSufficiencyMarkdown,
	},
];

function splice(source: string, key: string, body: string): string | null {
	const begin = `<!-- econ:begin ${key} -->`;
	const end = `<!-- econ:end ${key} -->`;
	const i = source.indexOf(begin);
	const k = source.indexOf(end);
	if (i === -1 || k === -1) return null;
	const note = "<!-- GENERATED by `bun run econ:figures` — do not edit by hand. -->";
	return `${source.slice(0, i + begin.length)}\n${note}\n\n${body}\n\n${source.slice(k)}`;
}

async function reconcile(path: string, next: string, label: string) {
	const current = existsSync(path) ? await readFile(path, "utf8") : "";
	if (current === next) return;
	if (check) {
		failures.push(label);
		return;
	}
	await writeFile(path, next);
	console.log(`  wrote ${label}`);
}

// ── run ──────────────────────────────────────────────────────────────────────
console.log(
	`econ-figures: SEED_PRICE=$${SEED_PRICE} TIME_POOL_PER_SEED=$${TIME_POOL_PER_SEED} CARD=${(CARD_RATE * 100).toFixed(1)}%+$${CARD_FLAT.toFixed(2)}`,
);

await reconcile(
	join(REPO, "packages/shared/src/figures.generated.ts"),
	await formatted(renderModule()),
	"packages/shared/src/figures.generated.ts",
);

if (!existsSync(VAULT)) {
	console.log("  (vault not present — skipping wiki blocks)");
} else {
	const byFile = new Map<string, string>();
	for (const b of BLOCKS) {
		const path = join(VAULT, b.file);
		if (!existsSync(path)) {
			console.warn(`  ! missing ${b.file}`);
			continue;
		}
		const current = byFile.get(path) ?? (await readFile(path, "utf8"));
		const next = splice(current, b.key, b.render());
		if (next === null) {
			console.warn(`  ! no <!-- econ:begin ${b.key} --> markers in ${b.file}`);
			continue;
		}
		byFile.set(path, next);
	}
	for (const [path, next] of byFile) {
		await reconcile(path, next, path.slice(VAULT.length + 1));
	}
}

if (check && failures.length > 0) {
	console.error("\necon-figures --check FAILED. These are stale:\n");
	for (const f of failures) console.error(`  ${f}`);
	console.error("\nRun `bun run econ:figures` and commit the result.");
	process.exit(1);
}
console.log(check ? "econ-figures: up to date" : "econ-figures: done");
