// SPDX-License-Identifier: AGPL-3.0-or-later
/**
 * Render every published money figure from the model, into both places that quote it.
 *
 *   bun run econ:figures           # write
 *   bun run econ:figures --check   # fail if anything has drifted (CI / make verify)
 *
 * Two outputs:
 *
 *  1. `packages/shared/src/figures.generated.ts` — plain numbers for the app. Plain,
 *     because **the SPA bundle must never import `fees.ts`**: that is the one import
 *     that pulls decimal.js in. Generating the figures gets derivation without the
 *     dependency, which is why this is a codegen step rather than a runtime import.
 *
 *     To check that it stayed out, do NOT grep the bundle for `toDecimalPlaces` —
 *     recharts ships **decimal.js-light**, which has that method too, so the obvious
 *     test reports a leak that isn't there (it fooled me on 2026-08-08). Grep for
 *     `cbrt` or `toFraction`, which only full decimal.js has. Both are 0 today.
 *
 *  2. The wiki tables and the sample receipt, and the money section of this repo's own
 *     `README.md`, written between HTML-comment markers in the docs that publish them.
 *     Same pattern the vault already uses for roadmap bars: generated regions are never
 *     hand-edited. The two run on different conditions — see `REPO_BLOCKS`.
 *
 * And one guard, which is neither:
 *
 *  3. A scan of the app source and the repo's published markdown for figures that were
 *     TYPED rather than read from (1), plus copy describing a mechanism the code no
 *     longer has. Markers are how a generated region gets covered, because markdown
 *     cannot import; everything around it needs the opposite shape — not "regenerate
 *     this region" but "no region may hold a typed figure at all". See `scanApp` /
 *     `scanDocs`, which share `scanText`.
 *
 * Why it exists: the 2026-08-03 pricing revamp swept these by hand and missed three
 * of them, which then sat in the "source of truth" doc overstating the remainder by
 * exactly the card fee for five days. A sweep cannot be trusted to be complete.
 *
 * Why (3) exists: because (1) and (2) were both green on 2026-08-12 while five
 * marketing pages published $9.40 against a model that said $9.41, and still called
 * the buyer's first download a deduction four months after it stopped being one.
 * A generated-figures guard only covers what it is pointed at, and nothing said the
 * app was outside it.
 */
import { existsSync } from "node:fs";
import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, relative } from "node:path";
import {
	CARD_FLAT,
	CARD_RATE,
	FREE_STORAGE_GIB,
	SALES_TAX_RATE,
	SEED_PRICE,
	TIME_POOL_PER_SEED,
} from "../packages/shared/src/constants.js";
import { FREE_PUBLIC_ACCESS_HOURS } from "../packages/shared/src/public-access.js";
import {
	badgeTable,
	cartSaving,
	creatorReceipt,
	directedSeedWorstCase,
	FIXED_MONTHLY_OVERHEAD,
	PAYING_BADGE_MIX,
	purchaseExamples,
	RIVAL_STOREFRONTS,
	saleTable,
	sampleReceipt,
	selfSufficiency,
	takeHomeComparison,
} from "../packages/shared/src/scenarios.js";

const REPO = join(import.meta.dir, "..");
const VAULT = join(process.env.HOME ?? "", "Obsidian/40-59 PhD Projects/43 Platforms/Anthers");

const check = process.argv.includes("--check");
/** Generated regions that no longer match what the model says. */
const failures: string[] = [];
/** Published figures found typed into the app by hand. */
const typed: string[] = [];
/** App copy describing a charge the model no longer has. */
const retired: string[] = [];
/** Files carrying `econ:allow-file`, reported every run so an exemption stays visible. */
const exempt: string[] = [];

/**
 * Run the rendered module through Biome before writing it.
 *
 * Without this the generator and the linter disagree — `--check` passes while
 * `bun run lint` fails on the file the generator just produced, which is a
 * maddening way to break the build. Formatting here means the two can never
 * diverge, whatever Biome's style settings become later.
 */
async function formatted(source: string): Promise<string> {
	const proc = Bun.spawn(["bunx", "biome", "format", "--stdin-file-path=figures.generated.ts"], {
		stdin: new TextEncoder().encode(source),
		stdout: "pipe",
		stderr: "pipe",
	});
	const out = await new Response(proc.stdout).text();
	if ((await proc.exited) !== 0) {
		console.error(await new Response(proc.stderr).text());
		throw new Error("biome format failed on the generated module");
	}
	return out;
}

// ── 1. The generated module the app reads ────────────────────────────────────
function renderModule(): string {
	const badges = badgeTable();
	const sales = saleTable();
	const receipt = sampleReceipt();
	const seed = directedSeedWorstCase();
	const j = (v: unknown) => JSON.stringify(v, null, "\t").replace(/\n/g, "\n");
	return `// SPDX-License-Identifier: AGPL-3.0-or-later
//
// GENERATED by scripts/econ-figures.ts — do not edit.
// Run \`bun run econ:figures\` after changing a dial in constants.ts or a formula
// in fees.ts. \`make verify\` fails if this file is stale.
//
// These are plain numbers on purpose: the app must not import fees.ts, which would
// pull decimal.js into the SPA bundle. Derivation happens at build time instead.

/**
 * Per-Badge decomposition of the monthly charge. Exact, not illustrative — it stopped
 * depending on a reference streamer's watch-hours when the bandwidth term went.
 */
export const BADGE_TABLE = ${j(badges)} as const;

/**
 * Direct-sale take-homes. \`sizeGiB\` is context for the row, NOT an input to the money:
 * delivery is free, so two rows at the same price agree whatever their size.
 */
export const SALE_TABLE = ${j(sales)} as const;

/** The sample monthly receipt: a Sprout who also directs two Seeds. */
export const SAMPLE_RECEIPT = ${j(receipt)} as const;

/** A lone directed Seed — the worst case, and what creator-facing copy quotes. */
export const DIRECTED_SEED_WORST_CASE = ${j(seed)} as const;
`;
}

// ── 2. The wiki blocks ───────────────────────────────────────────────────────

/**
 * Emit a table in the vault's house style: an empty trailing column and an empty
 * trailing row.
 *
 * Not decoration — it is a legibility rule for **edit mode**, which is where this
 * vault is actually read and written. Without them the rightmost column runs to the
 * edge of the pane and the last row abuts whatever follows. The vault's CLAUDE.md
 * requires generators to emit them precisely so a generated table doesn't fight the
 * convention on every run and produce a diff the moment a human touches the file.
 */
function table(head: string[], align: string[], rows: string[][]): string {
	const line = (cells: string[]) => `| ${cells.join(" | ")} |     |`;
	return [
		line(head),
		`|${align.map((a) => `${a}|`).join("")}---|`,
		...rows.map(line),
		`|${head.map(() => "  |").join("")}     |`,
	].join("\n");
}

/**
 * A plain markdown table, for the files that are read on GitHub rather than in Obsidian.
 *
 * Deliberately not `table()` above: that one emits the vault's trailing empty column and
 * row, which is a legibility rule for Obsidian's **edit mode** and reads as a rendering
 * bug anywhere else. Same data, different house style — so the README gets its own.
 */
function plainTable(head: string[], align: string[], rows: string[][]): string {
	return [
		`| ${head.join(" | ")} |`,
		`|${align.map((a) => `${a}|`).join("")}`,
		...rows.map((cells) => `| ${cells.join(" | ")} |`),
	].join("\n");
}

/**
 * The money section of the repo's own README.
 *
 * The README is the file most likely to be read by someone who has neither the vault nor
 * the app running, and until 2026-08-14 it was the *only* published surface with no guard
 * at all — so it taught a bandwidth allowance, a per-GiB rate and a pay-by-watch-time
 * Time Pool for two days after all three were deleted, in the repo's shop window. It has
 * a generated region now for the same reason the wiki does: a sweep cannot be trusted to
 * be complete, and the only figure that cannot drift is one nobody typed.
 */
function renderReadmeModelMarkdown(): string {
	const badges = badgeTable();
	const sales = [...new Map(saleTable().map((r) => [r.price, r])).values()];
	const seed = directedSeedWorstCase();
	return [
		`**Where a Seed given to Anthers goes.** Every row conserves exactly — creator pay plus the at-cost card line plus what is left equals what you paid. The remainder is the residual, so it absorbs any change in the other two while creator pay stays fixed.`,
		"",
		plainTable(
			[
				"Badge",
				"Seeds to Anthers",
				"You pay",
				"Time Pool → creators",
				"Payments\\*",
				"Free access & programs",
			],
			[":--", "--:", "--:", "--:", "--:", "--:"],
			badges.map((r) => [
				`**${r.badge}**`,
				String(r.seeds),
				`$${r.charge}`,
				`$${r.timePool}`,
				`$${r.payments}`,
				`**$${r.remainder}**`,
			]),
		),
		"",
		`\\* Card processing, at ${(CARD_RATE * 100).toFixed(1)}% + $${CARD_FLAT.toFixed(2)}, paid to Stripe and charged once per transaction. The flat part does not scale with the Seed count, which is why the remainder grows faster than linearly. **No row depends on how much anyone watches** — delivery costs $0 at any volume, so these are exact figures rather than a scenario.`,
		"",
		`Every account watches **${FREE_PUBLIC_ACCESS_HOURS} hours of Public Access a month, free forever** — no trial, no expiry. One Seed given to Anthers removes the limit, and no Seed above the first buys any more access.`,
		"",
		`**What a creator takes home.** Anthers keeps **$0.00** from every row; the only deduction is Stripe's card fee.`,
		"",
		plainTable(
			["Sale", "Creator receives", "Card"],
			[":--", "--:", "--:"],
			sales.map((r) => [
				`$${r.price} ${r.sizeGiB > 0 ? "digital" : "physical"}`,
				`**$${r.creatorReceives}**`,
				`$${r.cardFee}`,
			]),
		),
		"",
		`A directed Seed is the same shape: $${seed.gross} gross, $${seed.cardFee} card, **$${seed.net}** to the creator — that being the worst case, since batching several Seeds onto one monthly charge pays every creator on it more. Download size does not appear because it changes nothing: every download of a purchased work is included, forever, on any number of devices. Creator storage is the only creator-side charge — the first ${FREE_STORAGE_GIB} GiB free, then the object-store rate plus half again, and that half is what funds free access and the programs.`,
	].join("\n");
}

function renderBadgeMarkdown(): string {
	const rows = badgeTable();
	return [
		table(
			["Badge", "Seeds given to Anthers", "Charge", "Time Pool", "Payments\\*", "→ Remainder"],
			[":--", "--:", "--:", "--:", "--:", "--:"],
			rows.map((r) => [
				`**${r.badge}**`,
				String(r.seeds),
				`$${r.charge}`,
				`$${r.timePool}`,
				`$${r.payments}`,
				`**$${r.remainder}**`,
			]),
		),
		"",
		`\\* **Payments is INSIDE the charge** (since 2026-08-03), charged once per transaction at ${(CARD_RATE * 100).toFixed(1)}% + $${CARD_FLAT.toFixed(2)} and split pro-rata. Because the $${CARD_FLAT.toFixed(2)} is fixed per charge rather than per Seed, it does not scale with the Seed count — which is why the remainder grows faster than linearly.`,
		"",
		`Every row conserves exactly: Time Pool + Payments + remainder = the charge. **The remainder is the residual**, so it absorbs any change in the other two while creator pay stays fixed.`,
		"",
		`**No row depends on how much anyone watches.** A *Bandwidth* column sat between the charge and the Time Pool until 2026-08-12, priced off a representative streamer's watch-hours — so every remainder here was a scenario rather than a figure. Delivery costs $0 on R2 at any volume, so the column is gone and these numbers are exact. Watching more is free, and it takes nothing from the mission.`,
	].join("\n");
}

function renderReceiptMarkdown(): string {
	const r = sampleReceipt();
	const pad = (label: string, amount: string) =>
		`${label}${" ".repeat(Math.max(1, 62 - label.length - amount.length))}${amount}`;
	return [
		"```",
		"Your Anthers — February 2026",
		"",
		"━".repeat(66),
		pad(
			`Seeds to creators (${r.creatorSeeds} × $${SEED_PRICE}.00, directed by you)`,
			`$${r.directedGross}`,
		),
		pad(
			`  → reaching them, less their $${r.paymentsCreator} share of the card fee`,
			`$${r.directedNet}`,
		),
		"",
		pad(
			`Seeds given to Anthers (${r.anthersSeeds} · Sprout)`,
			`$${(r.anthersSeeds * SEED_PRICE).toFixed(2)}`,
		),
		// "creators you spent time with", not "creators you watched", and "by time" rather
		// than "by watch-time": the platform hosts four media and measures them on one
		// clock. Naming the video one makes it the default unit of a thing it is a quarter
		// of. This is a GENERATED block, so editing the wiki by hand is worse than useless —
		// the next `econ:figures` run puts the old wording straight back.
		pad("  Time Pool → creators you spent time with (by time)", `$${r.timePool}`),
		pad("  Payments → this side's share of the card fee (at cost)", `$${r.paymentsAnthers}`),
		pad("  Free access & programs (the remainder)", `$${r.remainder}`),
		"─".repeat(66),
		pad("Seeds subtotal (all-in)", `$${r.seedsSubtotal}`),
		pad(
			`Sales tax (${(SALES_TAX_RATE * 100).toFixed(1)}%, the only thing added on top)`,
			`+$${r.salesTax}`,
		),
		`${" ".repeat(56)}──────`,
		pad("Total billed (prepaid, monthly)", `$${r.totalBilled}`),
		"",
		`To creators this month: $${r.toCreators}  ·  Free access & programs: $${r.remainder}  ·  Anthers keeps: $0.00`,
		"```",
	].join("\n");
}

function renderSaleMarkdown(): string {
	// One row per list price. Size used to split them — a $10 1 GiB game and a $10
	// 2 GiB game took home different amounts — and since 2026-08-12 it doesn't, so
	// keeping both would print the same row twice.
	const rows = [...new Map(saleTable().map((r) => [r.price, r])).values()];
	const seed = directedSeedWorstCase();
	return [
		table(
			["Sale", "Creator receives", "Card"],
			[":--", "--:", "--:"],
			rows.map((r) => [
				`$${r.price} ${r.sizeGiB > 0 ? "digital" : "physical"}`,
				`**$${r.creatorReceives}**`,
				`$${r.cardFee}`,
			]),
		),
		"",
		`**Download size does not appear, because it no longer changes anything.** A digital sale used to carry the first download's bandwidth at cost, and redownloads drew the buyer's own allowance; delivery is free on R2, so every download of a purchased work is included, forever, on any number of devices.`,
		"",
		`A lone directed Seed is the same shape: $${seed.gross} gross, $${seed.cardFee} card, **$${seed.net}** to the creator. Batching Seeds onto one monthly charge pays every creator on it more, because the $${CARD_FLAT.toFixed(2)} is fixed per charge.`,
		"",
		`Anthers keeps **$0.00** from every row. Creator storage is the only creator-side charge: the first ${FREE_STORAGE_GIB} GiB free, then the object-store rate plus half again.`,
	].join("\n");
}

/**
 * The creator-facing worked examples, and what a cart is worth at the small end.
 *
 * This table is the one a creator reads before deciding whether to sell here, and it
 * was typed by hand in two docs — including the Copy Style Guide, inside the very rule
 * that forbids re-typing a figure from another page.
 */
function renderPurchaseExamplesMarkdown(): string {
	const rows = purchaseExamples();
	const cart = cartSaving();
	return [
		table(
			["Item", "List", "Size", "Card", "**Creator receives**", "Deduction"],
			[":--", "--:", "--:", "--:", "--:", "--:"],
			rows.map((r) => [
				r.item,
				`$${r.price}`,
				r.sizeLabel,
				`$${r.cardFee}`,
				`**$${r.creatorReceives}**`,
				r.deductionPct,
			]),
		),
		"",
		`**The deduction is Stripe's card fee and nothing else** — ${(CARD_RATE * 100).toFixed(1)}% + a flat $${CARD_FLAT.toFixed(2)}, paid to Stripe, with Anthers keeping $0.00 from every row. The flat part is what the percentages track: it is the whole reason a $${rows[0].price} track loses ${rows[0].deductionPct} while a $${rows[rows.length - 1].price} game loses ${rows[rows.length - 1].deductionPct}.`,
		"",
		`**Size is in the table for scale, not for money.** A digital sale used to deduct the first download's delivery at cost as well; delivery is free since 2026-08-12, so a ${rows[rows.length - 1].sizeLabel} work and a ${rows[0].sizeLabel} one at the same price pay their creator exactly the same, and every later download costs nobody anything.`,
		"",
		`**The cart is the mechanism that fixes the small end.** ${cart.count} $${cart.unitPrice} tracks bought separately lose **$${cart.separately}** to card fees; bought in one cart they lose **$${cart.inOneCart}**, and every cent of that difference goes to the creators.`,
	].join("\n");
}

/** A mid-size creator's monthly earnings, and the only cost that comes out of them. */
function renderCreatorReceiptMarkdown(): string {
	const r = creatorReceipt();
	const pad = (label: string, amount: string) =>
		`${label}${" ".repeat(Math.max(1, 62 - label.length - amount.length))}${amount}`;
	return [
		"```",
		"Your Earnings — February 2026                                  @LifeOfRiza",
		"",
		"━".repeat(66),
		pad("Time Pool (by time spent) + directed Seeds (net of card)", `$${r.gross}`),
		pad(
			`Storage (${r.libraryGiB} GiB library − ${r.freeGiB} GiB free = ${r.billableGiB} GiB, at cost)`,
			`−$${r.storage}`,
		),
		pad("Delivery (unlimited, at any volume)", "$0.00"),
		pad("Storage charge (half again)", `−$${r.storageCharge}`),
		`${" ".repeat(54)}──────────`,
		pad("Net earnings", `$${r.net}`),
		"",
		"Payouts carry no processing (Connect transfers are free); the only",
		"deduction from a directed Seed is its share of the card fee.",
		"```",
	].join("\n");
}

/** Whether the charitable budget funds itself, as a function of the paying share. */
function renderSelfSufficiencyMarkdown(): string {
	const s = selfSufficiency();
	const mix = Object.entries(PAYING_BADGE_MIX)
		.map(([seeds, share]) => `${(Number(share) * 100).toFixed(0)}% at ${seeds}`)
		.join(", ");
	return [
		`Charitable revenue is **$${s.revenuePerPayingUser} per paying user per month**, and each paying user also carries the free-access cost of the free users beside them — **$${s.freeUserCost}/month each**, which is the subsidised Time Pool a free account funds for the creators it watches. So everything turns on the **paying share**:`,
		"",
		table(
			["Paying share", "Net per paying user", "Users to solvency"],
			["--:", "--:", "--:"],
			s.rows.map((r) => [
				r.sharePct,
				r.net.startsWith("-") ? `−$${r.net.slice(1)}` : `$${r.net}`,
				r.usersToSolvency === null ? "**never**" : `~${r.usersToSolvency.toLocaleString("en-US")}`,
			]),
		),
		"",
		`**Below roughly ${s.breakEvenPct} paying, growth never closes the gap** — each new cohort costs more in free access than it brings in, so scale makes the problem worse rather than better. Above it the model self-funds, and the scale required falls away quickly.`,
		"",
		`**That floor no longer moves with how much free users watch**, and until 2026-08-12 it did. A free account's cost was its streaming bandwidth plus its Time Pool, so the generosity of the free floor and the platform's self-sufficiency were the same dial and raising one priced the other. Delivery is free on R2, the floor is gone, and what remains — the $${s.freeUserCost} Time Pool — is a flat cost per free account however much it watches. **Free access stopped having a usage-dependent price.**`,
		"",
		`Two ASSUMPTIONS drive every number here and neither is a dial: the paying-user Badge mix (${mix} Seeds) and $${FIXED_MONTHLY_OVERHEAD.toLocaleString("en-US")}/month of fixed overhead. The mix matters more than it looks — the remainder a paying user generates rises **faster than linearly** with their Seed count, because the fixed $${CARD_FLAT.toFixed(2)} of the card fee does not scale with it.`,
	].join("\n");
}

/**
 * 62.04's headline table: what reaches a creator here versus on each storefront.
 *
 * This block is why the task existed. The Anthers column was a **hand-mirror** of the
 * generated figures — the doc said so in its own warning — and it went a cent low
 * everywhere the day the delivery charge was retired, because a mirror only reflects
 * when someone remembers to polish it. Two competitor cells were a cent out too, in
 * the other direction: they rounded the card fee at the end of the row while ours
 * rounded it first, so a single table disagreed with itself about one number.
 */
function renderTakeHomeMarkdown(): string {
	const rows = takeHomeComparison();
	const bold = (v: string | null, best: string) =>
		v === null ? "—" : v === best ? `**$${v}**` : `$${v}`;
	return [
		table(
			["List price", "**Anthers**", ...RIVAL_STOREFRONTS.map((r) => r.name)],
			["--:", ...RIVAL_STOREFRONTS.map(() => "--:"), "--:"],
			rows.map((r) => [
				`$${r.price}`,
				bold(r.anthers, r.best),
				...r.rivals.map((v) => bold(v.net, r.best)),
			]),
		),
		"",
		`Every column is **all-in take-home at the same list price** — each rival's figure includes the same ${(CARD_RATE * 100).toFixed(1)}% + $${CARD_FLAT.toFixed(2)} card cost we itemise, because every platform pays it. Comparing our all-in against a competitor's headline cut would flatter us exactly where a creator would check.`,
		"",
		`**The bold cell is the best row, and it is computed rather than chosen.** Steam returns more than us at $${rows[0].price}: their ${(RIVAL_STOREFRONTS[0].share * 100).toFixed(0)}% of a small sale is less than the flat card fee they absorb, so a percentage model beats a flat-fee model at the very bottom. Conceding that is what makes the rest of the table believable, and generating it means we cannot quietly stop conceding it when a dial moves.`,
		"",
		`⚠️ **Competitor rates are perishable** — they live in \`RIVAL_STOREFRONTS\` in \`packages/shared/src/scenarios.ts\`, were last checked 2026-08-03, and a storefront can change one without telling us. Re-check before anything ships. Only the arithmetic is guaranteed here; the rates are an input.`,
	].join("\n");
}

interface Block {
	file: string;
	key: string;
	render: () => string;
}

/**
 * Generated regions in markdown that lives in **this repository**.
 *
 * Kept apart from `BLOCKS` because of when each one runs: the wiki blocks are skipped
 * entirely when the vault is absent, which is correct for a document only Parker has and
 * exactly wrong for one every clone carries. CI has no vault, so a README block on the
 * wiki path would never once be checked — and "never checked" is the state the README was
 * already in.
 */
const REPO_BLOCKS: Block[] = [
	{ file: "README.md", key: "readme-model", render: renderReadmeModelMarkdown },
];

const BLOCKS: Block[] = [
	{
		file: "50-59 Business and Finance/50 Economics & Model/50.01 Support Model Economics and Milestones.md",
		key: "badge-table",
		render: renderBadgeMarkdown,
	},
	{
		file: "50-59 Business and Finance/50 Economics & Model/50.01 Support Model Economics and Milestones.md",
		key: "sample-receipt",
		render: renderReceiptMarkdown,
	},
	{
		file: "50-59 Business and Finance/50 Economics & Model/50.01 Support Model Economics and Milestones.md",
		key: "sale-table",
		render: renderSaleMarkdown,
	},
	{
		file: "20-29 User Experience/20 Support Model/20.01 Badges and Seed Levels.md",
		key: "badge-table",
		render: renderBadgeMarkdown,
	},
	{
		file: "30-39 Creator Experience/31 Monetization/31.02 Direct Creator Purchases.md",
		key: "purchase-examples",
		render: renderPurchaseExamplesMarkdown,
	},
	{
		file: "60-69 Strategy/63 Brand/63.01 Copy Style Guide.md",
		key: "sale-table",
		render: renderSaleMarkdown,
	},
	{
		file: "50-59 Business and Finance/50 Economics & Model/50.01 Support Model Economics and Milestones.md",
		key: "creator-receipt",
		render: renderCreatorReceiptMarkdown,
	},
	{
		file: "10-19 Overview/11 Model & Mission/11.02 Free Access and Charitable Programs.md",
		key: "self-sufficiency",
		render: renderSelfSufficiencyMarkdown,
	},
	{
		file: "60-69 Strategy/62 Positioning & Audience/62.04 Creator Take-Home Comparisons.md",
		key: "take-home",
		render: renderTakeHomeMarkdown,
	},
];

// ── 3. The app: a published figure may be DERIVED, never TYPED ───────────────
//
// The app reads its figures from `figures.generated.ts`, and an import cannot
// drift — so the residual risk is not a stale region, it is someone typing a
// number that is right today. This scan is what closes that, and it is worth being
// exact about the guarantee, because a guard whose reach is misread is how we got
// here in the first place:
//
//   It catches a published figure at the moment it is TYPED, while it still matches
//   the model. It does NOT recognise one that has already gone stale — $9.40 matches
//   nothing we publish now, so nothing here would have flagged it today. It would
//   have flagged it on the day it was written, when it was still correct.
//
// That is the right place to catch it. Typing is the defect; drifting is only what
// the defect eventually does.

const APP_ROOTS = ["apps/web/src", "packages/web-shared/src"];

/**
 * Markdown in this repo that is read by outsiders, and so is held to the same standard
 * as a page.
 *
 * The README needed **both** halves of the guard and had neither. It carried typed money
 * figures (a $0.01/GiB rate, a per-Badge Time Pool column) *and* retired-mechanism prose
 * with no number attached — "pays creators by watch-time", a bandwidth allowance, a Badge
 * that gated content — for anywhere from two days to five months after each mechanism was
 * deleted. It drifted precisely because `APP_ROOTS` is a list of `.ts`/`.tsx` directories
 * and nobody noticed the repo's shop window was outside it.
 */
const DOC_FILES = ["README.md"];

/**
 * Copy for a charge that no longer exists.
 *
 * This is NOT a copy linter — 63.01 is the guide, and adding every rule there to a
 * build script would rot. It is the second half of one specific defect, and it earns
 * its place because the figure scan above could not have found it: *"the only
 * deductions are card processing and your buyer's first download"* carries no number,
 * so a page can quote a perfectly current $9.41 while still describing a fee retired
 * four months earlier. That exact sentence survived this task's own sweep and turned
 * up in a bundle grep afterwards.
 *
 * The rule for adding one: a phrase belongs here when it describes a **mechanism the
 * code no longer has**, so that the only correct number of occurrences is zero.
 *
 * 🚨 **Every pattern must exclude the negation**, or the guard fires on the one use
 * that is always correct. *"No wallet, no per-GiB charge, however many devices you
 * use"* is exactly the sentence a retired charge should leave behind, and four pages
 * say some version of it. A first cut without the lookbehind flagged all four — which
 * would have taught us to annotate good copy rather than fix bad copy, and that is how
 * a guard becomes noise people route around.
 */
const NOT_NEGATED = /(?<!\b(?:no|never|not|without|nor|zero) )/.source;
const RETIRED_COPY: { pattern: RegExp; why: string }[] = [
	{
		pattern: new RegExp(`${NOT_NEGATED}(?:buyer'?s? )?first download`, "gi"),
		why: "delivery has been free at any volume since 2026-08-12 — there is no first-download charge to deduct",
	},
	{
		pattern: new RegExp(
			`${NOT_NEGATED}(?:bandwidth (?:allowance|wallet)|per-GiB (?:charge|rate))`,
			"gi",
		),
		why: "the allowance, the wallet and the per-GiB rate were all deleted 2026-08-12",
	},
	{
		// A mechanism the code never had, rather than one it lost — but the test the list
		// applies is the same ("the only correct number of occurrences is zero"), and so is
		// the fix. ATProto adoption is deferred (41.01): what ships is Bluesky identity
		// LINKING, and the `atproto_uri` columns sit unpopulated as future-proofing. This
		// framing has drifted back onto marketing pages twice — PR #166 removed it from
		// /for-creators, #183 from the Ghost comparison — which is what earns it a guard
		// rather than another sweep.
		//
		// ⚠️ Deliberately narrow: it matches the CLAIM, not the subject. A page may say
		// federation is coming, may name Bluesky, may explain what ATProto is. What it may
		// not say is that Anthers is built on it today.
		pattern: new RegExp(
			`${NOT_NEGATED}(?:built on the AT ?Protocol|portable DID|stored as ATProto records)`,
			"gi",
		),
		why: "ATProto adoption is deferred — Bluesky identity linking ships, federation does not (41.01)",
	},
	{
		// Not a retired *mechanism* like the two above — a retired *word* for a live one,
		// which is the other way this list earns its keep. The Time Pool is real; calling
		// what it measures "watch-time" makes video the default unit of a platform that
		// hosts four media and measures them on one clock. 63.01 blessed the word until
		// 2026-08-12 **while citing the equal-time principle as its authority**, which
		// refutes itself in a line.
		//
		// ⚠️ Scoped to user-facing copy, exactly as 63.01 is. This scanner only walks
		// `APP_ROOTS` and blanks comments first, so the engineering uses it deliberately
		// keeps — `distribute-pool.ts`'s job comments, the ~600 Class B reads per
		// watch-hour figure — are out of reach by construction rather than by exception.
		pattern: new RegExp(`${NOT_NEGATED}watch[- ](?:time|hours?)`, "gi"),
		why: 'a minute is a minute across four media — say "time" (63.01 § Vocabulary)',
	},
	{
		// Retired 2026-08-12 with the second access table (migration `0029`). There is one
		// gate primitive and it points only at a creator: a Work is gated by its creator or
		// it is Public Access, with no Badge threshold in between. `ANTHERS_BADGES` no
		// longer participates in resolution at all, so this describes a mechanism the code
		// genuinely no longer has — the test this list applies.
		//
		// ⚠️ Earned by measurement, not suspicion: on 2026-08-14 this phrase was still live
		// in five places across /for-users, /for-creators and /faq, two days after the
		// mechanism was deleted, and every one of them carried a correct money figure. That
		// is precisely the defect the figure scan cannot see.
		//
		// The lookahead spares the sentence the retirement *leaves behind* — "Seeds you give
		// Anthers gate nothing at all" is the correct copy now, and a guard that flagged it
		// would teach people to annotate good copy rather than delete bad copy.
		pattern: new RegExp(
			`${NOT_NEGATED}Anthers[- ](?:[Gg]ates?\\b(?!\\s+(?:nothing|no\\b))|gated)`,
			"g",
		),
		why: "Anthers Gates were retired 2026-08-12 — one gate primitive, pointed only at a creator (63.01 § Seed Gate)",
	},
	{
		// The other half of the same 2026-08-12 change, and the subtler one. Deleting the
		// bandwidth allowance made "no allowance, no cap" true of *delivery* — and the copy
		// correctly said so. What the copy never learned is that a NEW meter arrived the
		// same day: Public Access is capped monthly on a free account. So four pages ended
		// up claiming unbounded streaming while the app itself rendered the limit.
		//
		// 🚨 Downloads really are unlimited, so this must not fire on them. It matches only
		// the retired formulations that put STREAMING inside the unbounded claim — 63.01
		// makes "free forever" and the limit co-present, on the same rule as "no cut" and
		// the take-home.
		pattern: new RegExp(
			`${NOT_NEGATED}(?:stream(?:s|ing)?[^.]{0,30}without a meter|stream(?:ing|s)? and download(?:s|ing)? are unlimited|streams and downloads freely)`,
			"gi",
		),
		why: "a free account's Public Access is capped monthly — say the limit beside the freedom (63.01 § Claims: co-presence)",
	},
];

/** `// econ:allow — <why>`: this number is not one of ours. The reason is required. */
const ALLOW = /econ:allow(?!-file)\b[\s:—-]*(.*)$/;

/**
 * `// econ:allow-file — <why>`: this whole file is a known exception.
 *
 * A file-level escape hatch is how guards go quiet, so it pays for itself two ways:
 * the reason is required, and **every exempt file is printed on every run**, in both
 * write and check mode. An exception you have to read out loud each time is one
 * somebody eventually fixes; a silenced line is one nobody sees again.
 */
// The `m` flag matters: without it `$` only anchors at end-of-STRING, so a marker
// in a file header would never match the file it heads.
const ALLOW_FILE = /econ:allow-file\b[\s:—-]*(.*)$/m;

/**
 * Find the annotation covering line `i`: on the line itself, or anywhere in the
 * comment block immediately above it — the reason for a coincidence is often two
 * lines, and a guard that silently ignores the second one teaches people to write
 * shorter reasons rather than better ones.
 *
 * `code` is the comment-blanked source, so "this line is nothing but a comment" is
 * exactly "blank once the comments are gone, but not blank before".
 */
function allowance(lines: string[], code: string[], i: number): RegExpExecArray | null {
	let found = ALLOW.exec(lines[i]);
	for (let k = i - 1; !found && k >= 0 && code[k].trim() === "" && lines[k].trim() !== ""; k--) {
		found = ALLOW.exec(lines[k]);
	}
	return found;
}

/**
 * Every money figure `scenarios.ts` publishes, indexed by its rendered value and
 * mapped to the name a page should read it by.
 *
 * Built from the scenarios rather than from `figures.generated.ts`, so a stale
 * generated file can never satisfy the guard that guards it.
 */
function publishedFigures(): Map<string, string[]> {
	const index = new Map<string, string[]>();
	const add = (value: unknown, name: string) => {
		if (typeof value !== "string" || !/^\d+\.\d{2}$/.test(value)) return;
		const at = index.get(value) ?? [];
		if (!at.includes(name)) at.push(name);
		index.set(value, at);
	};
	const record = (owner: string, row: Record<string, unknown>, keyField?: string) => {
		const at = keyField ? `${owner}[${row[keyField]}]` : owner;
		for (const [k, v] of Object.entries(row)) add(v, `${at}.${k}`);
	};
	// The two dials prose quotes directly, named first so the message points at the
	// import a page actually wants rather than at the table row that happens to equal it.
	add(SEED_PRICE.toFixed(2), "SEED_PRICE (@anthers/shared/constants)");
	add(TIME_POOL_PER_SEED.toFixed(2), "TIME_POOL_PER_SEED (@anthers/shared/constants)");
	for (const r of badgeTable()) record("BADGE_TABLE", r, "badge");
	for (const r of saleTable()) record("SALE_TABLE", r, "label");
	for (const r of purchaseExamples()) record("purchaseExamples()", r, "label");
	record("SAMPLE_RECEIPT", sampleReceipt());
	record("DIRECTED_SEED_WORST_CASE", directedSeedWorstCase());
	record("cartSaving()", cartSaving());
	record("creatorReceipt()", creatorReceipt());
	const s = selfSufficiency();
	add(s.freeUserCost, "selfSufficiency().freeUserCost");
	add(s.revenuePerPayingUser, "selfSufficiency().revenuePerPayingUser");
	for (const r of s.rows) add(r.net, `selfSufficiency().rows[${r.sharePct}].net`);
	return index;
}

/**
 * Blank every comment, preserving newlines so line numbers stay true.
 *
 * These pages carry long doc comments that explain the model in figures — developer
 * prose no reader ever sees, and flagging it would only push us toward worse
 * comments. There is deliberately no TypeScript parse here: a real lexer would have
 * to know that the apostrophe in JSX text like `Anthers' cut` is not a string
 * delimiter, and mis-reading that fails in the wrong direction. Blanking only ever
 * REMOVES text, so the worst a mis-read can cost is a missed hit — never a false
 * accusation against a line that is fine.
 */
function withoutComments(src: string): string {
	let out = "";
	for (let i = 0; i < src.length; ) {
		if (src.startsWith("/*", i)) {
			const end = src.indexOf("*/", i + 2);
			const stop = end === -1 ? src.length : end + 2;
			for (let k = i; k < stop; k++) out += src[k] === "\n" ? "\n" : " ";
			i = stop;
		} else if (src.startsWith("//", i) && src[i - 1] !== ":") {
			// The `:` guard keeps `https://…` inside a string from reading as a comment.
			const end = src.indexOf("\n", i);
			const stop = end === -1 ? src.length : end;
			out += " ".repeat(stop - i);
			i = stop;
		} else {
			out += src[i++];
		}
	}
	return out;
}

/**
 * Collapse the source to one line, keeping a char→line map.
 *
 * JSX text wraps wherever the formatter decides, so a phrase and the word that negates
 * it routinely end up on different lines: `no allowance, no wallet, no per-GiB\ncharge`
 * splits "per-GiB charge" itself in half AND strands its "no" two lines up. Matching
 * line-by-line therefore reports a sentence that says the exact opposite of what it was
 * accused of — which is worse than missing it, because the fix looks like deleting
 * correct copy. Phrase rules run against the unwrapped text; only the report needs
 * lines, and `lineOf` carries them.
 */
function flatten(code: string): { text: string; lineOf: number[] } {
	let text = "";
	const lineOf: number[] = [];
	let line = 1;
	let gap = false;
	for (const ch of code) {
		if (ch === "\n") {
			line++;
			gap = true;
			continue;
		}
		if (/\s/.test(ch)) {
			gap = true;
			continue;
		}
		if (gap && text) {
			text += " ";
			lineOf.push(line);
		}
		gap = false;
		text += ch;
		lineOf.push(line);
	}
	return { text, lineOf };
}

async function* sourceFiles(dir: string): AsyncGenerator<string> {
	for (const entry of await readdir(dir, { withFileTypes: true })) {
		const path = join(dir, entry.name);
		if (entry.isDirectory()) yield* sourceFiles(path);
		else if (/\.tsx?$/.test(entry.name) && !/\.(test|spec|e2e)\.tsx?$/.test(entry.name)) yield path;
	}
}

/**
 * Blank a markdown file down to the prose a human actually wrote.
 *
 * Two exclusions, and they are excluded for the same reason rather than two: a generated
 * region is **full** of published figures — that is its entire job — and the sentences its
 * renderers emit name retired mechanisms on purpose ("a *Bandwidth* column sat here until
 * 2026-08-12"). Scanning either would report the generator against itself, and teach the
 * reader to annotate correct output rather than fix incorrect prose. HTML comments go for
 * the same reason `withoutComments` blanks `//` ones: an `econ:allow` reason is written
 * there, and `allowance()` finds an annotation above a line by asking whether that line is
 * blank *once comments are gone but not before*.
 *
 * Newlines survive so reported line numbers stay true.
 */
function withoutGeneratedRegions(src: string): string {
	const blank = (s: string) => s.replace(/[^\n]/g, " ");
	return src
		.replace(/<!--\s*econ:begin\b[\s\S]*?econ:end\b[\s\S]*?-->/g, blank)
		.replace(/<!--[\s\S]*?-->/g, blank);
}

/**
 * Both halves of the guard against one file: a published figure typed by hand, and copy
 * for a mechanism the code no longer has.
 *
 * `source` is what a human wrote and `prose` is that with the unscannable parts blanked —
 * comments for code, generated regions for markdown. Keeping both is what lets the figure
 * check run over the real text while the `econ:allow` reason is still found in the comment
 * that carries it.
 */
function scanText(label: string, source: string, prose: string, index: Map<string, string[]>) {
	const lines = source.split("\n");
	const code = prose.split("\n");
	code.forEach((line, i) => {
		for (const m of line.matchAll(/\$(\d+\.\d{2})/g)) {
			const owners = index.get(m[1]);
			if (!owners) continue;
			// The annotation lives in a comment, so it is looked for in the ORIGINAL.
			const allow = allowance(lines, code, i);
			if (allow?.[1].trim()) continue;
			typed.push(
				`${label}:${i + 1}\n      typed $${m[1]} — that is ${owners
					.slice(0, 3)
					.join(" / ")}${allow ? "\n      (econ:allow needs a reason after it)" : ""}`,
			);
		}
	});

	const { text, lineOf } = flatten(prose);
	for (const { pattern, why } of RETIRED_COPY) {
		for (const hit of text.matchAll(pattern)) {
			const at = lineOf[hit.index] ?? 1;
			const allow = allowance(lines, code, at - 1);
			if (allow?.[1].trim()) continue;
			retired.push(`${label}:${at}\n      "${hit[0]}" — ${why}`);
		}
	}
}

async function scanApp() {
	const index = publishedFigures();
	for (const root of APP_ROOTS) {
		const dir = join(REPO, root);
		if (!existsSync(dir)) continue;
		for await (const path of sourceFiles(dir)) {
			const source = await readFile(path, "utf8");
			const fileWide = ALLOW_FILE.exec(source);
			if (fileWide?.[1].trim()) {
				exempt.push(`${relative(REPO, path)} — ${fileWide[1].trim()}`);
				continue;
			}
			scanText(relative(REPO, path), source, withoutComments(source), index);
		}
	}
}

async function scanDocs() {
	const index = publishedFigures();
	for (const file of DOC_FILES) {
		const path = join(REPO, file);
		if (!existsSync(path)) continue;
		const source = await readFile(path, "utf8");
		const fileWide = ALLOW_FILE.exec(source);
		if (fileWide?.[1].trim()) {
			exempt.push(`${file} — ${fileWide[1].trim()}`);
			continue;
		}
		scanText(file, source, withoutGeneratedRegions(source), index);
	}
}

function splice(source: string, key: string, body: string): string | null {
	const begin = `<!-- econ:begin ${key} -->`;
	const end = `<!-- econ:end ${key} -->`;
	const i = source.indexOf(begin);
	const k = source.indexOf(end);
	if (i === -1 || k === -1) return null;
	const note = "<!-- GENERATED by `bun run econ:figures` — do not edit by hand. -->";
	return `${source.slice(0, i + begin.length)}\n${note}\n\n${body}\n\n${source.slice(k)}`;
}

async function reconcile(path: string, next: string, label: string) {
	const current = existsSync(path) ? await readFile(path, "utf8") : "";
	if (current === next) return;
	if (check) {
		failures.push(label);
		return;
	}
	await writeFile(path, next);
	console.log(`  wrote ${label}`);
}

// ── run ──────────────────────────────────────────────────────────────────────
console.log(
	`econ-figures: SEED_PRICE=$${SEED_PRICE} TIME_POOL_PER_SEED=$${TIME_POOL_PER_SEED} CARD=${(CARD_RATE * 100).toFixed(1)}%+$${CARD_FLAT.toFixed(2)}`,
);

await reconcile(
	join(REPO, "packages/shared/src/figures.generated.ts"),
	await formatted(renderModule()),
	"packages/shared/src/figures.generated.ts",
);

/**
 * Splice every block for `root` and write the files that changed.
 *
 * One file may carry several blocks (50.01 carries four), so the spliced text is
 * accumulated per path before anything is written — otherwise the second block would
 * splice into the on-disk copy and drop the first.
 */
async function writeBlocks(root: string, blocks: Block[]) {
	const byFile = new Map<string, string>();
	for (const b of blocks) {
		const path = join(root, b.file);
		if (!existsSync(path)) {
			console.warn(`  ! missing ${b.file}`);
			continue;
		}
		const current = byFile.get(path) ?? (await readFile(path, "utf8"));
		const next = splice(current, b.key, b.render());
		if (next === null) {
			console.warn(`  ! no <!-- econ:begin ${b.key} --> markers in ${b.file}`);
			continue;
		}
		byFile.set(path, next);
	}
	for (const [path, next] of byFile) {
		await reconcile(path, next, relative(root, path));
	}
}

// The repo's own markdown first, and unconditionally: every clone has it, CI has it, and
// a contributor with no vault still gets the check. The wiki is the optional half.
await writeBlocks(REPO, REPO_BLOCKS);

if (!existsSync(VAULT)) {
	console.log("  (vault not present — skipping wiki blocks)");
} else {
	await writeBlocks(VAULT, BLOCKS);
}

await scanApp();
await scanDocs();

if (failures.length > 0) {
	console.error("\nThese generated regions are stale:\n");
	for (const f of failures) console.error(`  ${f}`);
	console.error("\nRun `bun run econ:figures` and commit the result.");
}

if (typed.length > 0) {
	console.error("\nA published figure may be DERIVED, never typed:\n");
	for (const t of typed) console.error(`  ${t}`);
	console.error(
		"\nIn the app, read it from `@anthers/shared/figures` instead — the way FAQPage\n" +
			"does. In markdown, move it inside an `econ:begin`/`econ:end` region and render\n" +
			"it from a scenario, the way the README's money section is.\n" +
			"If the number is not one of ours (a rival platform's cut, an illustrative\n" +
			"infrastructure cost), say so on the line:\n" +
			"    // econ:allow — Steam's 30% cut, not one of our figures\n" +
			"    <!-- econ:allow — Steam's 30% cut, not one of our figures -->\n",
	);
}

if (retired.length > 0) {
	// The list holds two kinds now — a mechanism the code no longer has, and a word we
	// no longer use for one it does — so the header names neither and the per-hit `why`
	// carries the difference. Saying "a charge that no longer exists" over a vocabulary
	// hit sends the reader looking for a number to update, which is the wrong move.
	console.error("\nThis copy uses something we have retired:\n");
	for (const r of retired) console.error(`  ${r}`);
	console.error(
		"\nStrike the retired phrasing rather than updating a number beside it — the\n" +
			"sentence changes shape, it does not change value. If the phrase is genuinely\n" +
			"someone else's (a rival's mechanism, their metric) or historical, annotate it:\n" +
			"    // econ:allow — YouTube's own metric for YouTube's own mechanism\n",
	);
}

if (exempt.length > 0) {
	console.log(`\necon-figures: ${exempt.length} file(s) exempt from the app scan:`);
	for (const e of exempt) console.log(`  ${e}`);
	console.log("");
}

if (check && failures.length + typed.length + retired.length > 0) {
	console.error("econ-figures --check FAILED.");
	process.exit(1);
}
console.log(check ? "econ-figures: up to date" : "econ-figures: done");
