// SPDX-License-Identifier: AGPL-3.0-or-later
/**
 * Render every published money figure from the model, into both places that quote it.
 *
 *   bun run econ:figures           # write
 *   bun run econ:figures --check   # fail if anything has drifted (CI / make verify)
 *
 * Two outputs:
 *
 *  1. `packages/shared/src/figures.generated.ts` — plain numbers for the app. Plain,
 *     because **the SPA bundle must never import `fees.ts`**: that is the one import
 *     that pulls decimal.js in. Generating the figures gets derivation without the
 *     dependency, which is why this is a codegen step rather than a runtime import.
 *
 *     To check that it stayed out, do NOT grep the bundle for `toDecimalPlaces` —
 *     recharts ships **decimal.js-light**, which has that method too, so the obvious
 *     test reports a leak that isn't there (it fooled me on 2026-08-08). Grep for
 *     `cbrt` or `toFraction`, which only full decimal.js has. Both are 0 today.
 *
 *  2. The wiki tables and the sample receipt, written between HTML-comment markers
 *     in the docs that publish them. Same pattern the vault already uses for roadmap
 *     bars: generated regions are never hand-edited.
 *
 * Why it exists: the 2026-08-03 pricing revamp swept these by hand and missed three
 * of them, which then sat in the "source of truth" doc overstating the remainder by
 * exactly the card fee for five days. A sweep cannot be trusted to be complete.
 */
import { existsSync } from "node:fs";
import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import {
	BANDWIDTH_PER_GIB,
	CARD_FLAT,
	CARD_RATE,
	DELIVERY_GIB_PER_HOUR,
	FREE_STORAGE_GIB,
	SALES_TAX_RATE,
	SEED_PRICE,
	TIME_POOL_PER_SEED,
} from "../packages/shared/src/constants.js";
import {
	badgeTable,
	directedSeedWorstCase,
	saleTable,
	sampleReceipt,
} from "../packages/shared/src/scenarios.js";

const REPO = join(import.meta.dir, "..");
const VAULT = join(process.env.HOME ?? "", "Obsidian/40-59 PhD Projects/43 Platforms/Anthers");

const check = process.argv.includes("--check");
const failures: string[] = [];

/**
 * Run the rendered module through Biome before writing it.
 *
 * Without this the generator and the linter disagree — `--check` passes while
 * `bun run lint` fails on the file the generator just produced, which is a
 * maddening way to break the build. Formatting here means the two can never
 * diverge, whatever Biome's style settings become later.
 */
async function formatted(source: string): Promise<string> {
	const proc = Bun.spawn(["bunx", "biome", "format", "--stdin-file-path=figures.generated.ts"], {
		stdin: new TextEncoder().encode(source),
		stdout: "pipe",
		stderr: "pipe",
	});
	const out = await new Response(proc.stdout).text();
	if ((await proc.exited) !== 0) {
		console.error(await new Response(proc.stderr).text());
		throw new Error("biome format failed on the generated module");
	}
	return out;
}

// ── 1. The generated module the app reads ────────────────────────────────────
function renderModule(): string {
	const badges = badgeTable();
	const sales = saleTable();
	const receipt = sampleReceipt();
	const seed = directedSeedWorstCase();
	const j = (v: unknown) => JSON.stringify(v, null, "\t").replace(/\n/g, "\n");
	return `// SPDX-License-Identifier: AGPL-3.0-or-later
//
// GENERATED by scripts/econ-figures.ts — do not edit.
// Run \`bun run econ:figures\` after changing a dial in constants.ts or a formula
// in fees.ts. \`make verify\` fails if this file is stale.
//
// These are plain numbers on purpose: the app must not import fees.ts, which would
// pull decimal.js into the SPA bundle. Derivation happens at build time instead.

/** Per-Badge decomposition of the monthly charge, for the reference streamer. */
export const BADGE_TABLE = ${j(badges)} as const;

/** Direct-sale take-homes. \`sizeGiB\` is load-bearing — quote it alongside. */
export const SALE_TABLE = ${j(sales)} as const;

/** The sample monthly receipt: a Sprout who also directs two Seeds. */
export const SAMPLE_RECEIPT = ${j(receipt)} as const;

/** A lone directed Seed — the worst case, and what creator-facing copy quotes. */
export const DIRECTED_SEED_WORST_CASE = ${j(seed)} as const;
`;
}

// ── 2. The wiki blocks ───────────────────────────────────────────────────────
function renderBadgeMarkdown(): string {
	const rows = badgeTable();
	const head =
		"| Badge | Seeds given to Anthers | Charge | Bandwidth\\* | Time Pool | Payments\\*\\* | → Remainder |";
	const sep = "|:--|--:|--:|--:|--:|--:|--:|";
	const body = rows.map(
		(r) =>
			`| **${r.badge}** | ${r.seeds} | $${r.charge} | $${r.bandwidth} | $${r.timePool} | $${r.payments} | **$${r.remainder}** |`,
	);
	const hours = rows.map((r) => r.watchHours).join(" / ");
	return [
		head,
		sep,
		...body,
		"",
		`\\* **Bandwidth is at-cost *actual usage*** — shown for a representative streamer at ${hours} watch-hours of 1080p AV1 a month (${DELIVERY_GIB_PER_HOUR} GiB/hr at $${BANDWIDTH_PER_GIB.toFixed(2)}/GiB). It is a scenario, not a dial: change the hours and every remainder changes.`,
		"",
		`\\*\\* **Payments is INSIDE the charge** (since 2026-08-03), charged once per transaction at ${(CARD_RATE * 100).toFixed(1)}% + $${CARD_FLAT.toFixed(2)} and split pro-rata. Because the $${CARD_FLAT.toFixed(2)} is fixed per charge rather than per Seed, it does not scale with the Seed count — which is why the remainder grows faster than linearly.`,
		"",
		`Every row conserves exactly: bandwidth + Time Pool + Payments + remainder = the charge. **The remainder is the residual**, so it absorbs any change in the other three — a heavier streamer shrinks it while the creators they watch are paid exactly the same.`,
	].join("\n");
}

function renderReceiptMarkdown(): string {
	const r = sampleReceipt();
	const pad = (label: string, amount: string) =>
		`${label}${" ".repeat(Math.max(1, 62 - label.length - amount.length))}${amount}`;
	return [
		"```",
		"Your Anthers — February 2026",
		"",
		"━".repeat(66),
		pad(
			`Seeds to creators (${r.creatorSeeds} × $${SEED_PRICE}.00, directed by you)`,
			`$${r.directedGross}`,
		),
		pad(
			`  → reaching them, less their $${r.paymentsCreator} share of the card fee`,
			`$${r.directedNet}`,
		),
		"",
		pad(
			`Seeds given to Anthers (${r.anthersSeeds} · Sprout)`,
			`$${(r.anthersSeeds * SEED_PRICE).toFixed(2)}`,
		),
		pad("  Time Pool → creators you watched (by watch-time)", `$${r.timePool}`),
		pad("  Your bandwidth (at cost, inside allowance)", `$${r.bandwidth}`),
		pad("  Payments → this side's share of the card fee (at cost)", `$${r.paymentsAnthers}`),
		pad("  Free access & programs (the remainder)", `$${r.remainder}`),
		"─".repeat(66),
		pad("Seeds subtotal (all-in)", `$${r.seedsSubtotal}`),
		pad(
			`Sales tax (${(SALES_TAX_RATE * 100).toFixed(1)}%, the only thing added on top)`,
			`+$${r.salesTax}`,
		),
		`${" ".repeat(56)}──────`,
		pad("Total billed (prepaid, monthly)", `$${r.totalBilled}`),
		"",
		`To creators this month: $${r.toCreators}  ·  Free access & programs: $${r.remainder}  ·  Anthers keeps: $0.00`,
		"```",
	].join("\n");
}

function renderSaleMarkdown(): string {
	const rows = saleTable().filter((r) => !r.label.startsWith("album"));
	const seed = directedSeedWorstCase();
	return [
		"| Sale | Download | Creator receives | Card | Delivery |",
		"|:--|--:|--:|--:|--:|",
		...rows.map(
			(r) =>
				`| $${r.price} ${r.sizeGiB > 0 ? "digital" : "physical"} | ${r.sizeGiB > 0 ? `${r.sizeGiB} GiB` : "—"} | **$${r.creatorReceives}** | $${r.cardFee} | $${r.delivery} |`,
		),
		"",
		`A lone directed Seed is the same shape: $${seed.gross} gross, $${seed.cardFee} card, **$${seed.net}** to the creator. Batching Seeds onto one monthly charge pays every creator on it more, because the $${CARD_FLAT.toFixed(2)} is fixed per charge.`,
		"",
		`Anthers keeps **$0.00** from every row. Creator storage is the only creator-side charge: the first ${FREE_STORAGE_GIB} GiB free, then DigitalOcean's rate plus half again.`,
	].join("\n");
}

const BLOCKS: { file: string; key: string; render: () => string }[] = [
	{
		file: "50-59 Business and Finance/50 Economics & Model/50.01 Support Model Economics and Milestones.md",
		key: "badge-table",
		render: renderBadgeMarkdown,
	},
	{
		file: "50-59 Business and Finance/50 Economics & Model/50.01 Support Model Economics and Milestones.md",
		key: "sample-receipt",
		render: renderReceiptMarkdown,
	},
	{
		file: "50-59 Business and Finance/50 Economics & Model/50.01 Support Model Economics and Milestones.md",
		key: "sale-table",
		render: renderSaleMarkdown,
	},
	{
		file: "20-29 User Experience/20 Support Model/20.01 Badges and Seed Levels.md",
		key: "badge-table",
		render: renderBadgeMarkdown,
	},
];

function splice(source: string, key: string, body: string): string | null {
	const begin = `<!-- econ:begin ${key} -->`;
	const end = `<!-- econ:end ${key} -->`;
	const i = source.indexOf(begin);
	const k = source.indexOf(end);
	if (i === -1 || k === -1) return null;
	const note = "<!-- GENERATED by `bun run econ:figures` — do not edit by hand. -->";
	return `${source.slice(0, i + begin.length)}\n${note}\n\n${body}\n\n${source.slice(k)}`;
}

async function reconcile(path: string, next: string, label: string) {
	const current = existsSync(path) ? await readFile(path, "utf8") : "";
	if (current === next) return;
	if (check) {
		failures.push(label);
		return;
	}
	await writeFile(path, next);
	console.log(`  wrote ${label}`);
}

// ── run ──────────────────────────────────────────────────────────────────────
console.log(
	`econ-figures: SEED_PRICE=$${SEED_PRICE} TIME_POOL_PER_SEED=$${TIME_POOL_PER_SEED} CARD=${(CARD_RATE * 100).toFixed(1)}%+$${CARD_FLAT.toFixed(2)}`,
);

await reconcile(
	join(REPO, "packages/shared/src/figures.generated.ts"),
	await formatted(renderModule()),
	"packages/shared/src/figures.generated.ts",
);

if (!existsSync(VAULT)) {
	console.log("  (vault not present — skipping wiki blocks)");
} else {
	const byFile = new Map<string, string>();
	for (const b of BLOCKS) {
		const path = join(VAULT, b.file);
		if (!existsSync(path)) {
			console.warn(`  ! missing ${b.file}`);
			continue;
		}
		const current = byFile.get(path) ?? (await readFile(path, "utf8"));
		const next = splice(current, b.key, b.render());
		if (next === null) {
			console.warn(`  ! no <!-- econ:begin ${b.key} --> markers in ${b.file}`);
			continue;
		}
		byFile.set(path, next);
	}
	for (const [path, next] of byFile) {
		await reconcile(path, next, path.slice(VAULT.length + 1));
	}
}

if (check && failures.length > 0) {
	console.error("\necon-figures --check FAILED. These are stale:\n");
	for (const f of failures) console.error(`  ${f}`);
	console.error("\nRun `bun run econ:figures` and commit the result.");
	process.exit(1);
}
console.log(check ? "econ-figures: up to date" : "econ-figures: done");
