# Generated by Django 6.0.2 on 2026-02-25 08:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_add_atproto_uri'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['-view_count'], name='idx_project_views'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['-download_count'], name='idx_project_downloads'),
        ),
    ]
