# Generated by Django 6.0.2 on 2026-02-25 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_header_image_user_location_user_website_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='atproto_did',
            field=models.CharField(blank=True, help_text='Decentralized Identifier (e.g. did:plc:abc123)', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='atproto_handle',
            field=models.CharField(blank=True, default='', help_text='ATProto handle (e.g. alice.bsky.social)', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='atproto_pds_url',
            field=models.URLField(blank=True, default='', help_text='Personal Data Server URL'),
        ),
    ]
