/**
 * Combined state & local sales tax rates by US state (2026 estimates).
 * Source: Tax Foundation, "State and Local Sales Tax Rates, 2026."
 *
 * These are average combined rates (state + local). Actual rates may
 * vary by locality within each state.
 */
export const STATE_SALES_TAX_RATES: { state: string; rate: number }[] = [
  { state: "Alabama", rate: 0.0946 },
  { state: "Alaska", rate: 0.0182 },
  { state: "Arizona", rate: 0.0852 },
  { state: "Arkansas", rate: 0.0946 },
  { state: "California", rate: 0.0899 },
  { state: "Colorado", rate: 0.0789 },
  { state: "Connecticut", rate: 0.0635 },
  { state: "Delaware", rate: 0 },
  { state: "District of Columbia", rate: 0.06 },
  { state: "Florida", rate: 0.0698 },
  { state: "Georgia", rate: 0.0749 },
  { state: "Hawaii", rate: 0.045 },
  { state: "Idaho", rate: 0.0603 },
  { state: "Illinois", rate: 0.0896 },
  { state: "Indiana", rate: 0.07 },
  { state: "Iowa", rate: 0.0694 },
  { state: "Kansas", rate: 0.0869 },
  { state: "Kentucky", rate: 0.06 },
  { state: "Louisiana", rate: 0.1011 },
  { state: "Maine", rate: 0.055 },
  { state: "Maryland", rate: 0.06 },
  { state: "Massachusetts", rate: 0.0625 },
  { state: "Michigan", rate: 0.06 },
  { state: "Minnesota", rate: 0.0814 },
  { state: "Mississippi", rate: 0.0706 },
  { state: "Missouri", rate: 0.0844 },
  { state: "Montana", rate: 0 },
  { state: "Nebraska", rate: 0.0698 },
  { state: "Nevada", rate: 0.0824 },
  { state: "New Hampshire", rate: 0 },
  { state: "New Jersey", rate: 0.066 },
  { state: "New Mexico", rate: 0.0767 },
  { state: "New York", rate: 0.0854 },
  { state: "North Carolina", rate: 0.07 },
  { state: "North Dakota", rate: 0.0709 },
  { state: "Ohio", rate: 0.0729 },
  { state: "Oklahoma", rate: 0.0906 },
  { state: "Oregon", rate: 0 },
  { state: "Pennsylvania", rate: 0.0634 },
  { state: "Rhode Island", rate: 0.07 },
  { state: "South Carolina", rate: 0.0749 },
  { state: "South Dakota", rate: 0.0611 },
  { state: "Tennessee", rate: 0.0961 },
  { state: "Texas", rate: 0.082 },
  { state: "Utah", rate: 0.0742 },
  { state: "Vermont", rate: 0.0639 },
  { state: "Virginia", rate: 0.0577 },
  { state: "Washington", rate: 0.0951 },
  { state: "West Virginia", rate: 0.0659 },
  { state: "Wisconsin", rate: 0.0572 },
  { state: "Wyoming", rate: 0.0556 },
];
